/* GRCON — mascote contextual v4, usando apenas PNGs HD físicos. */
(function(root){"use strict";
const VERSION="4.0.0",STYLE_ID="grcon-mascot-system-style",GLOBAL_ID="grcon-brand-mascot",CONTEXTUAL_ID="grcon-context-mascot";
const SPRITE_URL=new URL("assets/mascot/grcon-mascot-sprite.png?v=4.0.0",document.baseURI).href;
const FALLBACK_URL=new URL("assets/mascot/grcon-mascot-default.png?v=4.0.0",document.baseURI).href;
const POSES=Object.freeze({default:{x:0,y:0,label:"Mascote institucional do GRCON"},analysis:{x:1,y:0,label:"Mascote analisando documentos"},search:{x:2,y:0,label:"Mascote pesquisando documentos"},check:{x:3,y:0,label:"Mascote conferindo informações"},history:{x:0,y:1,label:"Mascote consultando o histórico"},dashboard:{x:1,y:1,label:"Mascote analisando indicadores"},"sigem-pw":{x:2,y:1,label:"Mascote comparando SIGEM e ProjectWise"},egrdt:{x:3,y:1,label:"Mascote preparando uma eGRDT"},import:{x:0,y:2,label:"Mascote importando uma base"},report:{x:1,y:2,label:"Mascote preparando um relatório"},warning:{x:2,y:2,label:"Mascote em estado de atenção"},success:{x:3,y:2,label:"Mascote indicando operação concluída"},pending:{x:0,y:3,label:"Mascote aguardando processamento"},empty:{x:1,y:3,label:"Mascote indicando ausência de resultados"},quality:{x:2,y:3,label:"Mascote da Qualidade do GRCON"}});
const CONTEXTS=Object.freeze({control:{root:"#grdt-module",heading:".ops-page-heading",pose:"default"},requests:{root:"#requests-module",heading:".ops-page-heading",pose:"search"},pdfTools:{root:"#pdf-tools-module",heading:".pdf-merge-heading",pose:"report"},analysisHistory:{root:"#analysis-history-module",heading:".analysis-history-heading",pose:"dashboard"},history:{root:"#history-module",heading:".history-heading",pose:"history"},sigem:{root:"#sigem-module",heading:".sigem-heading",pose:"pending"},conference:{root:"#posting-conference-module",heading:".pc-heading",pose:"check"},sigemPw:{root:"#sigem-pw-dashboard-module",heading:".spw-page-heading",pose:"sigem-pw"}});
let override="",observer=null,scheduled=false,activeAssetUrl=SPRITE_URL;
function applyAsset(url,kind,img){activeAssetUrl=url;document.documentElement.style.setProperty("--grcon-mascot-image",`url("${url}")`);document.documentElement.dataset.grconMascotAsset=kind;if(img){document.documentElement.dataset.grconMascotNaturalWidth=String(img.naturalWidth||0);document.documentElement.dataset.grconMascotNaturalHeight=String(img.naturalHeight||0);if((img.naturalWidth||0)<2048||(img.naturalHeight||0)<2048)console.error("GRCON: asset do mascote abaixo de 2048 px.",img.naturalWidth,img.naturalHeight)}schedule()}
function loadAsset(){const s=new Image();s.decoding="async";s.onload=()=>applyAsset(SPRITE_URL,"sprite-hd-v4",s);s.onerror=()=>{console.warn("GRCON: sprite HD falhou; usando fallback HD.");const f=new Image();f.decoding="async";f.onload=()=>applyAsset(FALLBACK_URL,"fallback-hd-v4",f);f.onerror=()=>console.error("GRCON: sprite e fallback HD do mascote falharam.");f.src=FALLBACK_URL};s.src=SPRITE_URL}
function installStyles(){if(document.getElementById(STYLE_ID))return;document.documentElement.style.setProperty("--grcon-mascot-image",`url("${activeAssetUrl}")`);const s=document.createElement("style");s.id=STYLE_ID;s.textContent=`.grcon-brand-mascot,.grcon-mascot-context{--mx:0;--my:0;position:relative;display:inline-flex;flex:0 0 auto;align-items:center;justify-content:center;overflow:visible;pointer-events:none;user-select:none}.grcon-brand-mascot{width:clamp(3rem,4.2vw,4rem);height:clamp(3rem,4.2vw,4rem);margin-inline:-.1rem 0}.grcon-mascot-context{width:clamp(5rem,7vw,6.875rem);height:clamp(5rem,7vw,6.875rem);margin-inline-start:auto;align-self:center;isolation:isolate}.grcon-mascot-context::before{content:"";position:absolute;z-index:-1;inset:8%;border-radius:50%;background:radial-gradient(circle,color-mix(in srgb,var(--brand-100,#e4f2f8) 82%,transparent) 0 38%,transparent 72%)}.grcon-mascot-sprite{width:100%;height:100%;background-image:var(--grcon-mascot-image);background-repeat:no-repeat;background-size:400% 400%;background-position:calc(var(--mx)*33.333333%) calc(var(--my)*33.333333%);filter:drop-shadow(0 5px 12px rgb(12 32 48 / 18%));opacity:1}.grcon-mascot-heading{flex-wrap:wrap!important;overflow:visible!important;column-gap:clamp(.7rem,1.5vw,1.25rem)!important;row-gap:.55rem!important}html[data-theme="dark"] .grcon-mascot-sprite{filter:drop-shadow(0 6px 15px rgb(0 0 0 / 38%))}html[data-theme="dark"] .grcon-mascot-context::before{background:radial-gradient(circle,rgb(111 196 227 / 14%) 0 36%,transparent 72%)}@media(max-width:1100px){.grcon-brand-mascot{width:3.5rem;height:3.5rem}.grcon-mascot-context{width:6.25rem;height:6.25rem}}@media(max-width:850px){.grcon-mascot-context{width:5.5rem;height:5.5rem;margin-inline-start:0}}@media(max-width:620px){.grcon-brand-mascot{width:2.75rem;height:2.75rem}.grcon-mascot-context{width:5rem;height:5rem}.grcon-mascot-heading>.grcon-mascot-context{order:2}}@media(max-width:430px){.grcon-brand-mascot{width:2.5rem;height:2.5rem}.grcon-mascot-context{width:4.5rem;height:4.5rem}}`;document.head.appendChild(s)}
function setPose(n,pose){const p=POSES[pose]||POSES.default;n.dataset.pose=POSES[pose]?pose:"default";n.style.setProperty("--mx",p.x);n.style.setProperty("--my",p.y);if(n.getAttribute("aria-hidden")!=="true")n.setAttribute("aria-label",p.label)}
function make(id,cls,decorative){let n=document.getElementById(id);if(n)return n;n=document.createElement("span");n.id=id;n.className=cls;if(decorative)n.setAttribute("aria-hidden","true");else{n.setAttribute("role","img");n.setAttribute("aria-label",POSES.default.label)}const sp=document.createElement("span");sp.className="grcon-mascot-sprite";n.appendChild(sp);return n}
function visible(el){return!!el&&!el.hidden&&el.getAttribute("aria-hidden")!=="true"}
function activeContext(){for(const[name,c]of Object.entries(CONTEXTS)){const r=document.querySelector(c.root);if(visible(r))return{name,config:c,root:r}}return null}
function controlPose(){const d=document.getElementById("p1-confirm-dialog"),e=document.getElementById("egrdt-drawer"),p=document.getElementById("progress"),r=document.getElementById("results-section");if(visible(d)||(e&&e.getAttribute("aria-hidden")==="false"))return"egrdt";if(visible(p))return"pending";if(visible(r))return"analysis";return"default"}
function resolvePose(ctx){if(override&&POSES[override])return override;if(!ctx)return"default";return ctx.name==="control"?controlPose():ctx.config.pose}
function sync(){scheduled=false;installStyles();const brand=document.querySelector(".topbar .brand"),logo=brand&&brand.querySelector(".grcon-brand-mark");if(brand&&logo){const g=make(GLOBAL_ID,"grcon-brand-mascot",false);if(g.parentElement!==brand)logo.insertAdjacentElement("afterend",g);setPose(g,"default")}const ctx=activeContext();let m=document.getElementById(CONTEXTUAL_ID);if(!ctx){if(m)m.remove();return}const h=ctx.root.querySelector(ctx.config.heading);if(!h)return;h.classList.add("grcon-mascot-heading");m=make(CONTEXTUAL_ID,"grcon-mascot-context",true);if(m.parentElement!==h)h.appendChild(m);const pose=resolvePose(ctx);m.dataset.context=ctx.name;setPose(m,pose);document.documentElement.dataset.grconMascot=`contextual-v${VERSION}`;document.documentElement.dataset.grconMascotContext=ctx.name;document.documentElement.dataset.grconMascotPose=pose}
function schedule(){if(scheduled)return;scheduled=true;(root.requestAnimationFrame||root.setTimeout)(sync)}
function setState(pose){if(pose&&!POSES[pose])throw new Error(`Pose do mascote desconhecida: ${pose}`);override=pose||"";schedule()}
function installObserver(){if(observer||!document.body)return;observer=new MutationObserver(ms=>{for(const m of ms){if(m.type==="childList"||(m.type==="attributes"&&["hidden","aria-hidden","class","aria-selected"].includes(m.attributeName))){schedule();break}}});observer.observe(document.body,{childList:true,subtree:true,attributes:true,attributeFilter:["hidden","aria-hidden","class","aria-selected"]});document.addEventListener("click",e=>{if(e.target.closest("[data-grcon-view],[data-pc-open],[data-spw-open]"))schedule()},true);["grcon:triage-rendered","grcon:conference-updated","grcon:pw-base-updated"].forEach(ev=>root.addEventListener(ev,schedule))}
function init(){installStyles();loadAsset();sync();installObserver();root.setTimeout(schedule,250);root.setTimeout(schedule,900)}
root.GRCONMascot=Object.freeze({version:VERSION,poses:POSES,contexts:CONTEXTS,spriteUrl:SPRITE_URL,fallbackUrl:FALLBACK_URL,setState,clearState:()=>setState(""),refresh:schedule,installHeader:sync});
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init,{once:true});else init();
})(window);
