(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;root.GrconNormativeVersionRegistry=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const STATUSES=new Set(['active','outdated_candidate','unconfirmed','absent_from_catalog','superseded']);
const text=v=>String(v??'').trim();
const norm=v=>{const raw=text(v).toUpperCase().replace(/\s+/g,'');const m=raw.match(/^N-?0*(\d{1,4})$/);return m?`N-${String(Number(m[1])).padStart(4,'0')}`:raw;};
const part=v=>{const x=text(v||'body').toUpperCase().replace(/\s+/g,' ');return x==='BODY'||x==='CORPO'?'BODY':x;};
const key=(n,p)=>`${norm(n)}::${part(p)}`;
function normalizeEntry(v){const s=v||{};const e={norm:norm(s.norm),part:part(s.part),revision:text(s.revision).toUpperCase(),edition:text(s.edition),catalogRevision:text(s.catalogRevision).toUpperCase(),catalogEdition:text(s.catalogEdition),title:text(s.title),status:text(s.status||'unconfirmed'),verificationSource:text(s.verificationSource),notes:text(s.notes)};if(!e.norm||!e.revision)throw new Error('Versão normativa exige norma e revisão.');if(!STATUSES.has(e.status))throw new Error(`Status de versão inválido: ${e.status}.`);return Object.freeze(e);}
function createVersionRegistry(seed=[]){const map=new Map();const register=(v,opt={})=>{const e=normalizeEntry(v),k=key(e.norm,e.part);if(map.has(k)&&!opt.replace)throw new Error(`Versão normativa duplicada: ${k}.`);map.set(k,e);return e;};const get=(n,p)=>map.get(key(n,p))||null;const list=n=>Object.freeze([...map.values()].filter(e=>!n||e.norm===norm(n)));const promotionDecision=(eOrNorm,p)=>{const e=typeof eOrNorm==='object'&&eOrNorm?eOrNorm:get(eOrNorm,p);if(!e)return Object.freeze({allowed:false,code:'missing_version',reason:'Versão normativa não cadastrada.'});if(e.status!=='active')return Object.freeze({allowed:false,code:e.status,reason:`Fonte normativa com status ${e.status}; promoção automática bloqueada.`});if(e.catalogRevision&&e.catalogRevision!==e.revision)return Object.freeze({allowed:false,code:'catalog_mismatch',reason:`Revisão ${e.revision} diverge do Catálogo ${e.catalogRevision}.`});return Object.freeze({allowed:true,code:'active',reason:'Versão normativa confirmada.'});};seed.forEach(register);return Object.freeze({register,get,list,promotionDecision,isUsable:(n,p)=>promotionDecision(n,p).allowed});}
const SEED=Object.freeze([
['N-2064','body','D','10/2017','D','10/2017','active','Catálogo PETROBRAS 09/2026'],
['N-1710','body','N','04/2020','N','04/2020','active','Catálogo PETROBRAS 09/2026'],
['N-1710','Anexo A','W','10/2023','','','active','Cabeçalho + Anexo G'],['N-1710','Anexo B','CJ','04/2025','','','active','Cabeçalho + Anexo G'],['N-1710','Anexo C','BF','12/2024','','','active','Cabeçalho + Anexo G'],['N-1710','Anexo D','BG','04/2025','','','active','Cabeçalho + Anexo G'],['N-1710','Anexo E','D','03/2010','','','active','Cabeçalho + Anexo G'],['N-1710','Anexo F','G','10/2014','','','active','Cabeçalho + Anexo G'],['N-1710','Anexo G','CN','04/2025','','','active','Cabeçalho'],
['N-0381','body','M','05/2022','M','05/2022','active','Catálogo PETROBRAS 09/2026'],['N-1692','body','D','04/2019','D','04/2019','active','Catálogo PETROBRAS 09/2026'],['N-1883','body','F','05/2024','F','05/2024','active','Catálogo PETROBRAS 09/2026'],['N-2040','body','F','03/2017','F','03/2017','active','Catálogo PETROBRAS 09/2026'],['N-1784','body','C','11/2011','C','11/2011','active','Catálogo PETROBRAS 09/2026'],['N-2301','body','E','11/2016','F','12/2025','outdated_candidate','Pacote x Catálogo 09/2026']
].map(([n,p,r,e,cr,ce,s,vs])=>normalizeEntry({norm:n,part:p,revision:r,edition:e,catalogRevision:cr,catalogEdition:ce,status:s,verificationSource:vs})));
return Object.freeze({STATUSES:Object.freeze([...STATUSES]),SEED,text,norm,part,normalizeEntry,createVersionRegistry});
});
