(function(root,factory){const R=root.GrconNormativeRegistry||(typeof module==='object'&&module.exports?require('./normative_registry.js'):null);const V=root.GrconNormativeVersionRegistry||(typeof module==='object'&&module.exports?require('./normative_version_registry.js'):null);const A=root.GrconNormativeApplicability||(typeof module==='object'&&module.exports?require('./normative_applicability.js'):null);const api=factory(R,V,A);if(typeof module==='object'&&module.exports)module.exports=api;root.GrconNormativeRuleEngine=api;})(typeof globalThis!=='undefined'?globalThis:this,function(R,V,A){
'use strict';if(!R||!V||!A)throw new Error('Infraestrutura normativa incompleta.');
const VERSION='normative-engine-1';const OUTCOME=Object.freeze({COMPLIANT:'CONFORME',WARNING:'ALERTA',BLOCK:'BLOQUEIO',NOT_APPLICABLE:'NÃO APLICÁVEL'});const text=v=>String(v??'').trim();
function base(rule,ctx,x={}){return Object.freeze({ruleId:rule.ruleId,norm:rule.norm,revision:rule.revision,section:rule.section,ruleType:rule.type,configuredSeverity:rule.severity,source:rule.source,document:text(ctx?.document),message:'',valueFound:'',valueExpected:'',overrideAllowed:rule.overrideAllowed===true,correctionHint:text(rule.correctionHint),...x});}
function evaluateRule(rule,ctx,evaluator,versions){const app=A.evaluate(rule,ctx);if(app.status===A.STATUS.NOT_APPLICABLE)return base(rule,ctx,{outcome:OUTCOME.NOT_APPLICABLE,code:'not_applicable',message:app.reason,applicability:app.status,overrideAllowed:false});if(app.status===A.STATUS.UNDETERMINED)return base(rule,ctx,{outcome:OUTCOME.WARNING,code:'applicability_undetermined',message:app.reason,applicability:app.status,missingContext:app.missing,overrideAllowed:false});const p=rule.source?.part||'body',entry=versions.get(rule.norm,p),decision=versions.promotionDecision(entry||rule.norm,p);if(!decision.allowed)return base(rule,ctx,{outcome:OUTCOME.WARNING,code:'source_not_promotable',message:decision.reason,sourceStatus:entry?.status||'missing',applicability:app.status,overrideAllowed:false});if(typeof evaluator!=='function')return base(rule,ctx,{outcome:OUTCOME.WARNING,code:'evaluator_missing',message:'Regra cadastrada sem avaliador; nenhuma decisão bloqueante foi tomada.',sourceStatus:entry.status,applicability:app.status,overrideAllowed:false});const raw=evaluator(ctx,rule)||{};if(raw.passed===true)return base(rule,ctx,{outcome:OUTCOME.COMPLIANT,code:text(raw.code||'compliant'),message:text(raw.message||'Regra atendida.'),valueFound:text(raw.valueFound),valueExpected:text(raw.valueExpected),sourceStatus:entry.status,applicability:app.status});const canBlock=rule.status==='active'&&rule.severity==='block'&&!['recommended','informational'].includes(rule.type);return base(rule,ctx,{outcome:canBlock?OUTCOME.BLOCK:OUTCOME.WARNING,code:text(raw.code||(canBlock?'rule_failed':'rule_warning')),message:text(raw.message||rule.description),valueFound:text(raw.valueFound),valueExpected:text(raw.valueExpected),sourceStatus:entry.status,applicability:app.status,overrideAllowed:canBlock&&rule.overrideAllowed===true});}
function snapshot(results,meta={}){const a=Array.isArray(results)?results:[],norms=new Map();for(const x of a)if(x.norm)norms.set(`${x.norm}|${x.revision}`,Object.freeze({norm:x.norm,revision:x.revision,sourceStatus:x.sourceStatus||''}));return Object.freeze({normativeValidationVersion:VERSION,generatedAt:text(meta.generatedAt)||new Date().toISOString(),rulesChecked:Object.freeze(a.map(x=>x.ruleId)),warnings:Object.freeze(a.filter(x=>x.outcome===OUTCOME.WARNING)),blocks:Object.freeze(a.filter(x=>x.outcome===OUTCOME.BLOCK)),normsApplied:Object.freeze([...norms.values()]),counts:Object.freeze({compliant:a.filter(x=>x.outcome===OUTCOME.COMPLIANT).length,warnings:a.filter(x=>x.outcome===OUTCOME.WARNING).length,blocks:a.filter(x=>x.outcome===OUTCOME.BLOCK).length,notApplicable:a.filter(x=>x.outcome===OUTCOME.NOT_APPLICABLE).length})});}
function createEngine(o={}){const registry=o.registry||R.createRegistry(),versions=o.versionRegistry||V.createVersionRegistry(V.SEED),evaluators=new Map(Object.entries(o.evaluators||{}));return Object.freeze({registry,versionRegistry:versions,registerEvaluator:(id,fn)=>{if(typeof fn!=='function')throw new Error('Avaliador deve ser função.');evaluators.set(text(id),fn);},evaluate:(ctx={},filters={})=>Object.freeze(registry.list({status:'active',...filters}).map(r=>evaluateRule(r,ctx,evaluators.get(r.ruleId),versions))),createSnapshot:snapshot});}
return Object.freeze({VERSION,OUTCOME,evaluateRule,createSnapshot:snapshot,createEngine});
});
