(function (root, factory) {
  const api = factory(root.GrconProjectWiseInventory, root.GrconProjectWiseReconciliation, root.GrconProjectWiseStorage, root.GrconProjectWiseReport);
  root.GrconProjectWiseUi = api;
})(typeof globalThis !== "undefined" ? globalThis : this, function (Inventory, Recon, Storage, Report) {
  "use strict";
  const state = { mounted:false, hydrated:false, sigem:null, projectwise:null, result:null, filtered:[], page:1, pageSize:200, dryRun:[], activeTab:"reconciliation" };
  function esc(value) { return String(value == null ? "" : value).replace(/[&<>"']/g, (c) => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c])); }
  function notify(message, kind) { if (typeof window.GrconNotify === "function") window.GrconNotify(message, kind || "info"); else if (kind === "error") console.error(message); else console.log(message); }
  function ensureStyle() { if (document.querySelector('link[data-projectwise-style]')) return; const link=document.createElement("link"); link.rel="stylesheet"; link.href="projectwise-reconciliation.css"; link.dataset.projectwiseStyle=""; document.head.appendChild(link); }
  function template() { return `<section id="projectwise-module" class="projectwise-module" hidden role="tabpanel" aria-label="Conferência SIGEM × ProjectWise">
    <header class="pw-heading"><div><span>CONFERÊNCIA DOCUMENTAL</span><h2>SIGEM × ProjectWise</h2><p>Descubra o passivo real antes de habilitar qualquer escrita no ProjectWise.</p></div><span class="pw-mode-badge"><i></i>Somente leitura · escrita bloqueada</span></header>
    <div class="pw-notice"><div><strong>Integração segura por etapas</strong><span>Esta entrega não armazena senha, não contorna SSO/MFA e não executa upload. A comparação usa a Consulta Geral SIGEM e um inventário/exportação do ProjectWise até que a API e a autenticação corporativas sejam confirmadas.</span></div></div>
    <div class="pw-source-grid"><section class="pw-card"><header><div><span>FONTE 1</span><strong>Consulta Geral SIGEM</strong></div><small>Obrigatória</small></header><label class="pw-file">Carregar planilha atualizada<input id="pw-sigem-file" type="file" accept=".xlsx,.xls,.xlsm,.csv"></label><small id="pw-sigem-meta" class="pw-source-meta">Nenhuma base carregada.</small></section>
    <section class="pw-card"><header><div><span>FONTE 2</span><strong>Inventário ProjectWise</strong></div><small>Leitura</small></header><label class="pw-file">Carregar exportação/inventário<input id="pw-inventory-file" type="file" accept=".xlsx,.xls,.xlsm,.csv,.json"></label><small id="pw-inventory-meta" class="pw-source-meta">Aceita planilha ou JSON exportado oficialmente.</small></section></div>
    <div class="pw-actions"><button class="primary-button" id="pw-run" type="button" disabled>Analisar passivo</button><button class="secondary-button" id="pw-export" type="button" disabled>Exportar Excel</button><button class="secondary-button" id="pw-dryrun" type="button" disabled>Gerar Dry Run</button><button class="text-button danger" id="pw-clear" type="button">Limpar análise</button><span id="pw-progress" aria-live="polite"></span></div>
    <section id="pw-dashboard" class="pw-dashboard" aria-label="Resumo da conciliação"></section>
    <div class="pw-queue-tabs" role="tablist" aria-label="Visão ProjectWise"><button class="secondary-button compact active" id="pw-tab-reconciliation" type="button" role="tab" aria-selected="true">Conciliação</button><button class="secondary-button compact" id="pw-tab-queue" type="button" role="tab" aria-selected="false">Fila ProjectWise</button></div>
    <section id="pw-results"><div class="pw-toolbar"><label><span>Busca geral</span><input id="pw-search" type="search" placeholder="Código, TAG, EAP, título ou pasta"></label><label><span>Situação</span><select id="pw-status"><option value="">Todas</option></select></label><label><span>Disciplina</span><select id="pw-discipline"><option value="">Todas</option></select></label><label><span>Tipo</span><select id="pw-type"><option value="">Todos</option></select></label><button class="secondary-button compact" id="pw-reset-filters" type="button">Limpar filtros</button></div>
    <div class="pw-batch"><label><span>Pesquisa em lote — um código por linha</span><textarea id="pw-batch-codes" placeholder="Cole vários códigos para comparar somente estes documentos"></textarea></label><button class="secondary-button" id="pw-apply-batch" type="button">Aplicar lista</button></div><div id="pw-result-host" class="pw-empty">Carregue as duas fontes para calcular o passivo.</div><div class="pw-pagination" id="pw-pagination" hidden><span id="pw-page-info"></span><div><button class="secondary-button compact" id="pw-prev" type="button">Anterior</button><button class="secondary-button compact" id="pw-next" type="button">Próxima</button></div></div></section>
    <details id="pw-dryrun-panel" class="pw-card pw-dryrun" hidden><summary>Plano de Dry Run — nenhuma operação é executada</summary><div id="pw-dryrun-host" class="pw-dryrun-grid"></div></details>
  </section>`; }
  function mount() { if (state.mounted) return; ensureStyle(); const main=document.getElementById("app-main"); if (!main) return; main.insertAdjacentHTML("beforeend", template()); state.mounted=true; bind(); }
  function statusLabel(value) { return ({MESMA_REVISAO:"Mesma revisão",REVISAO_PROJECTWISE_DESATUALIZADA:"PW com revisão anterior",PROJECTWISE_COM_REVISAO_SUPERIOR:"PW com revisão superior",NAO_ENCONTRADO_PROJECTWISE:"Não encontrado no ProjectWise",POSSIVEL_DUPLICIDADE:"Possível duplicidade",ASSOCIACAO_DUVIDOSA:"Associação duvidosa",CODIFICACAO_IRREGULAR:"Codificação irregular"})[value] || value || "—"; }
  function statusTone(value) { if (value===Recon.STATUSES.SAME_REVISION) return "ok"; if ([Recon.STATUSES.POSSIBLE_DUPLICATE,Recon.STATUSES.INVALID_CODE,Recon.STATUSES.PW_NEWER].includes(value)) return "danger"; if ([Recon.STATUSES.PW_OLDER,Recon.STATUSES.NOT_FOUND,Recon.STATUSES.DOUBTFUL].includes(value)) return "warn"; return "neutral"; }
  async function readFile(file, kind) { if (!file) throw new Error("Selecione um arquivo."); if (kind==="projectwise" && /\.json$/i.test(file.name)) { const parsed=Inventory.parseProjectWiseJson(await file.text(),{fileName:file.name,fileSize:file.size,lastModified:file.lastModified}); if (!parsed.ok) throw new Error(parsed.errors.join(" ")); return parsed; } if (!window.XLSX) throw new Error("Leitor XLSX indisponível."); const workbook=window.XLSX.read(await file.arrayBuffer(),{type:"array",cellDates:false}); const parsed=Inventory.parseWorkbook(workbook,kind,{fileName:file.name,fileSize:file.size,lastModified:file.lastModified}); if (!parsed.ok) throw new Error(parsed.errors.join(" ")); return parsed; }
  async function onSource(input, kind) { const file=input.files?.[0]; if (!file) return; const meta=document.getElementById(kind==="sigem"?"pw-sigem-meta":"pw-inventory-meta"); meta.textContent="Lendo arquivo…"; try { const parsed=await readFile(file,kind); if (kind==="sigem") state.sigem=parsed; else state.projectwise=parsed; const detected=Object.entries(parsed.meta.columns||{}).map(([k,v])=>`${k}: ${v}`).join(" · "); meta.textContent=`${parsed.meta.fileName||file.name} · ${parsed.records.length.toLocaleString("pt-BR")} registro(s) · ${parsed.meta.sheetName||"JSON"}${detected?` · ${detected}`:""}`; document.getElementById("pw-run").disabled=!(state.sigem?.ok&&state.projectwise?.ok); } catch(error) { meta.textContent=error.message||"Falha ao ler arquivo."; if(kind==="sigem")state.sigem=null;else state.projectwise=null; document.getElementById("pw-run").disabled=true; notify(error.message||"Falha ao ler a fonte.","error"); } }
  function metrics(s) { const items=[["Total SIGEM",s.totalSigem],["Encontrados PW",s.foundProjectWise],["Pendentes",s.notFound],["Mesma revisão",s.sameRevision],["Revisão divergente",s.revisionDifferent],["Duplicidade",s.duplicates],["Validação manual",s.manualValidation],["PW revisão anterior",s.pwOlder],["PW revisão superior",s.pwNewer],["Código irregular",s.invalidCode],["Aptos pela identidade",s.eligibleIdentity],["Aptos automáticos",s.automaticReady],["Taxa conciliada",`${s.reconciliationRate}%`]]; document.getElementById("pw-dashboard").innerHTML=items.map(([l,v])=>`<div class="pw-metric"><span>${esc(l)}</span><strong>${esc(Number.isFinite(v)?Number(v).toLocaleString("pt-BR"):v)}</strong></div>`).join(""); }
  function fillSelect(id, values, labeler) { const select=document.getElementById(id), current=select.value, first=select.options[0]?.outerHTML||'<option value="">Todos</option>'; select.innerHTML=first+[...new Set(values.filter(Boolean))].sort((a,b)=>String(a).localeCompare(String(b),"pt-BR")).map(v=>`<option value="${esc(v)}">${esc(labeler?labeler(v):v)}</option>`).join(""); if([...select.options].some(o=>o.value===current))select.value=current; }
  function refreshFilterOptions(){const rows=state.result?.rows||[];fillSelect("pw-status",rows.map(r=>r.status),statusLabel);fillSelect("pw-discipline",rows.map(r=>r.discipline));fillSelect("pw-type",rows.map(r=>r.documentType));}
  function activeRows(){let rows=state.result?.rows||[];if(state.activeTab==="queue")rows=rows.filter(r=>[Recon.ACTIONS.NEW_DOCUMENT,Recon.ACTIONS.NEW_REVISION,Recon.ACTIONS.MANUAL_REVIEW].includes(r.action));const box=document.getElementById("pw-batch-codes");const codes=box?.dataset.applied==="true"?box.value.split(/\r?\n/).map(v=>v.trim()).filter(Boolean):[];return Recon.filterRows(rows,{query:document.getElementById("pw-search")?.value||"",status:document.getElementById("pw-status")?.value||"",discipline:document.getElementById("pw-discipline")?.value||"",documentType:document.getElementById("pw-type")?.value||"",codes});}
  function renderTable(){if(!state.result)return;state.filtered=activeRows();const host=document.getElementById("pw-result-host"),pagination=document.getElementById("pw-pagination"),totalPages=Math.max(1,Math.ceil(state.filtered.length/state.pageSize));state.page=Math.min(Math.max(1,state.page),totalPages);const start=(state.page-1)*state.pageSize,pageRows=state.filtered.slice(start,start+state.pageSize);if(!pageRows.length){host.className="pw-empty";host.innerHTML="Nenhum documento corresponde aos filtros atuais.";pagination.hidden=true;return;}host.className="pw-table-wrap";host.innerHTML=`<table class="pw-table"><thead><tr><th>Situação</th><th>Código SIGEM</th><th>Rev. SIGEM</th><th>Rev. PW</th><th>EAP</th><th>Tipo</th><th>TAG</th><th>Disciplina</th><th>Código PW</th><th>ID PW</th><th>Caminho PW</th><th>Ação</th><th>Bloqueios / motivo</th></tr></thead><tbody>${pageRows.map(r=>`<tr><td><span class="pw-status ${statusTone(r.status)}">${esc(statusLabel(r.status))}</span></td><td><strong>${esc(r.sigemDocument)}</strong></td><td>${esc(r.sigemRevision)}</td><td>${esc(r.pwRevision||"—")}</td><td>${esc(r.eap||"—")}</td><td>${esc(r.documentType||"—")}</td><td>${esc(r.tag||"—")}</td><td>${esc(r.discipline||"—")}</td><td>${esc(r.pwDocument||"—")}</td><td>${esc(r.pwId||"—")}</td><td>${esc(r.pwPath||"—")}</td><td>${esc(r.action)}</td><td>${esc((r.blockers||[]).join("; "))}${r.blockers?.length?"<br>":""}<small>${esc(r.reason)}</small></td></tr>`).join("")}</tbody></table>`;pagination.hidden=false;document.getElementById("pw-page-info").textContent=`${(start+1).toLocaleString("pt-BR")}–${(start+pageRows.length).toLocaleString("pt-BR")} de ${state.filtered.length.toLocaleString("pt-BR")} · página ${state.page}/${totalPages}`;document.getElementById("pw-prev").disabled=state.page<=1;document.getElementById("pw-next").disabled=state.page>=totalPages;}
  function renderDryRun(){state.dryRun=Recon.dryRun(state.result?.rows||[]);const panel=document.getElementById("pw-dryrun-panel"),host=document.getElementById("pw-dryrun-host");panel.hidden=false;panel.open=true;host.innerHTML=state.dryRun.length?state.dryRun.slice(0,300).map(d=>`<div class="pw-dryrun-item"><div><strong>${esc(d.document)}</strong><small>Rev. ${esc(d.revision)} · ${esc(d.operation)}</small></div><div><strong>${d.executable?"Apto":"Bloqueado"}</strong><small>${esc((d.blockers||[]).join("; ")||"Sem bloqueios")}</small></div><div><strong>${esc(d.destination||"Destino não determinado")}</strong><small>${esc(d.file||"Arquivo não associado")}</small></div></div>`).join(""):'<div class="pw-empty">Nenhuma operação de postagem é necessária.</div>';}
  async function run(){if(!state.sigem?.ok||!state.projectwise?.ok)return;const progress=document.getElementById("pw-progress");progress.textContent="Conciliando documentos…";document.getElementById("pw-run").disabled=true;await new Promise(r=>setTimeout(r,0));try{state.result=Recon.reconcile(state.sigem.records,state.projectwise.records,{liveWriteEnabled:false});state.page=1;state.dryRun=Recon.dryRun(state.result.rows);metrics(state.result.summary);refreshFilterOptions();renderTable();document.getElementById("pw-export").disabled=false;document.getElementById("pw-dryrun").disabled=false;progress.textContent=`${state.result.summary.totalSigem.toLocaleString("pt-BR")} documento(s) analisado(s).`;try{await Storage.saveCurrent({result:state.result,sourceMeta:{sigem:state.sigem.meta,projectwise:state.projectwise.meta}});}catch(error){console.warn("[ProjectWise] snapshot local:",error);}notify(`Conferência concluída: ${state.result.summary.notFound.toLocaleString("pt-BR")} não encontrado(s) no ProjectWise.`,"success");}catch(error){progress.textContent="Falha na conciliação.";notify(error.message||"Não foi possível concluir a conciliação.","error");}finally{document.getElementById("pw-run").disabled=!(state.sigem?.ok&&state.projectwise?.ok);}}
  async function exportExcel(){if(!state.result)return;try{await Report.download(state.result,{fileName:"Conferencia_SIGEM_ProjectWise",dryRun:state.dryRun.length?state.dryRun:Recon.dryRun(state.result.rows),sourceMeta:{sigem:state.sigem?.meta||state.restoredMeta?.sigem,projectwise:state.projectwise?.meta||state.restoredMeta?.projectwise}});}catch(error){notify(error.message||"Falha ao gerar o Excel.","error");}}
  async function clearAnalysis(){state.result=null;state.filtered=[];state.dryRun=[];state.page=1;document.getElementById("pw-dashboard").innerHTML="";const host=document.getElementById("pw-result-host");host.className="pw-empty";host.innerHTML="Carregue as duas fontes para calcular o passivo.";document.getElementById("pw-pagination").hidden=true;document.getElementById("pw-dryrun-panel").hidden=true;document.getElementById("pw-export").disabled=true;document.getElementById("pw-dryrun").disabled=true;try{await Storage.clearCurrent();}catch(_){}}
  function setTab(tab){state.activeTab=tab;state.page=1;["reconciliation","queue"].forEach(name=>{const b=document.getElementById(`pw-tab-${name}`),active=name===tab;b?.classList.toggle("active",active);b?.setAttribute("aria-selected",String(active));});renderTable();}
  function bind(){document.getElementById("pw-sigem-file").addEventListener("change",e=>onSource(e.currentTarget,"sigem"));document.getElementById("pw-inventory-file").addEventListener("change",e=>onSource(e.currentTarget,"projectwise"));document.getElementById("pw-run").addEventListener("click",run);document.getElementById("pw-export").addEventListener("click",exportExcel);document.getElementById("pw-dryrun").addEventListener("click",renderDryRun);document.getElementById("pw-clear").addEventListener("click",clearAnalysis);["pw-search","pw-status","pw-discipline","pw-type"].forEach(id=>document.getElementById(id).addEventListener(id==="pw-search"?"input":"change",()=>{state.page=1;renderTable();}));document.getElementById("pw-reset-filters").addEventListener("click",()=>{["pw-search","pw-status","pw-discipline","pw-type"].forEach(id=>document.getElementById(id).value="");const box=document.getElementById("pw-batch-codes");box.value="";box.dataset.applied="false";state.page=1;renderTable();});document.getElementById("pw-apply-batch").addEventListener("click",()=>{const box=document.getElementById("pw-batch-codes");box.dataset.applied=box.value.trim()?"true":"false";state.page=1;renderTable();});document.getElementById("pw-prev").addEventListener("click",()=>{state.page-=1;renderTable();});document.getElementById("pw-next").addEventListener("click",()=>{state.page+=1;renderTable();});document.getElementById("pw-tab-reconciliation").addEventListener("click",()=>setTab("reconciliation"));document.getElementById("pw-tab-queue").addEventListener("click",()=>setTab("queue"));}
  async function hydrate(){if(state.hydrated)return;state.hydrated=true;try{const snapshot=await Storage.loadCurrent();if(!snapshot?.payload?.result)return;state.result=snapshot.payload.result;state.restoredMeta=snapshot.payload.sourceMeta||{};state.dryRun=Recon.dryRun(state.result.rows||[]);metrics(state.result.summary||Recon.summarize(state.result.rows||[]));refreshFilterOptions();renderTable();document.getElementById("pw-export").disabled=false;document.getElementById("pw-dryrun").disabled=false;document.getElementById("pw-progress").textContent=`Última conciliação restaurada · ${new Date(snapshot.savedAt).toLocaleString("pt-BR")}`;}catch(error){console.warn("[ProjectWise] restauração local:",error);}}
  async function activate(){mount();const module=document.getElementById("projectwise-module");if(module)module.hidden=false;await hydrate();}
  mount(); return Object.freeze({mount,activate,state});
});