(function (root) {
  "use strict";

  const Core = root.GrconSigemPwDashboard;
  const MODULE_ID = "sigem-pw-dashboard-module";
  const MACRO_CLASSES = Object.freeze(["ET", "N-1710", "CV"]);
  const RELATION_LABELS = Object.freeze({
    both: "Presentes nas duas bases",
    "sigem-only": "Exclusivos do SIGEM",
    "pw-only": "Exclusivos do PW",
    "non-comparable": "Não comparáveis",
  });
  const state = {
    ready: false,
    busy: false,
    sigem: { meta: null, records: [] },
    pw: { meta: null, records: [] },
    model: null,
    result: null,
    filters: { documentClass: "", sigemStatus: "", pwStatus: "", discipline: "", emission: "", relation: "" },
    drill: { relation: "", search: "", documentClass: "", discipline: "", status: "", emission: "" },
  };
  let shell = null;
  let refreshPromise = null;

  function text(value) { return value === null || value === undefined ? "" : String(value).trim(); }
  function norm(value) { return text(value).normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/[–—]/g, "-").toUpperCase().replace(/\s+/g, " ").trim(); }
  function escapeHtml(value) { return text(value).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;").replace(/'/g, "&#039;"); }
  function fmt(value) { return Number(value || 0).toLocaleString("pt-BR"); }
  function pct(value, total) {
    if (!Number.isFinite(Number(value)) || !Number.isFinite(Number(total)) || Number(total) <= 0) return "—";
    return `${(Number(value) / Number(total) * 100).toLocaleString("pt-BR", { minimumFractionDigits: 1, maximumFractionDigits: 1 })}%`;
  }
  function fmtDate(value) {
    const date = new Date(value);
    return value && !Number.isNaN(date.getTime()) ? new Intl.DateTimeFormat("pt-BR", { dateStyle: "short", timeStyle: "short" }).format(date) : "—";
  }
  function notify(message, kind) {
    if (typeof root.GrconNotify === "function") root.GrconNotify(message, kind || "info");
    else if (kind === "error") root.alert(message);
  }
  function icon(path) { return `<svg aria-hidden="true" viewBox="0 0 24 24"><path d="${path}"></path></svg>`; }
  function identityInfo(document) { try { return Core.documentIdentity(document?.document || "").info || null; } catch (_) { return null; } }
  function isComparable(document) {
    if (!MACRO_CLASSES.includes(text(document && document.documentClass))) return false;
    const info = identityInfo(document);
    return !(info?.eapApplicable && info.eapValid === false);
  }
  function currentStatus(document, kind) { return kind === "pw" ? text(document?.current?.state) : text(document?.current?.status); }
  function currentDiscipline(document) { return text(document?.current?.disciplineDesc || document?.current?.discipline); }
  function subsetMap(map, keys) { const output = new Map(); keys.forEach((key) => { if (map.has(key)) output.set(key, map.get(key)); }); return output; }
  function comparableMap(map) { return new Map([...map].filter(([, document]) => isComparable(document))); }
  function nonComparableMap(map) { return new Map([...map].filter(([, document]) => !isComparable(document))); }
  function setDifference(left, right) { const output = new Set(); left.forEach((key) => { if (!right.has(key)) output.add(key); }); return output; }
  function setIntersection(left, right) { const output = new Set(); left.forEach((key) => { if (right.has(key)) output.add(key); }); return output; }
  function relationSets(sigemMap, pwMap) {
    const sigemKeys = new Set(sigemMap.keys());
    const pwKeys = new Set(pwMap.keys());
    return { sigemKeys, pwKeys, both: setIntersection(sigemKeys, pwKeys), sigemOnly: setDifference(sigemKeys, pwKeys), pwOnly: setDifference(pwKeys, sigemKeys) };
  }
  function distribution(map, selector) {
    const counts = new Map();
    map.forEach((document) => { const label = text(selector(document)) || "Sem informação"; counts.set(label, (counts.get(label) || 0) + 1); });
    return [...counts.entries()].map(([label, count]) => ({ label, count })).sort((a, b) => b.count - a.count || a.label.localeCompare(b.label, "pt-BR"));
  }
  function classRows(sigemMap, pwMap) {
    return MACRO_CLASSES.map((documentClass) => {
      const sigem = new Map([...sigemMap].filter(([, document]) => document.documentClass === documentClass));
      const pw = new Map([...pwMap].filter(([, document]) => document.documentClass === documentClass));
      const sets = relationSets(sigem, pw);
      const emitted = [...pw.values()].filter((document) => document.emitted).length;
      return { documentClass, sigem: sigem.size, pwRegistered: pw.size, pwEmitted: emitted, matched: sets.both.size, exclusiveSigem: sets.sigemOnly.size, exclusivePw: sets.pwOnly.size, coverage: sigem.size ? sets.both.size / sigem.size : null, emissionRate: pw.size ? emitted / pw.size : null };
    }).filter((row) => row.sigem || row.pwRegistered);
  }

  function buildView() {
    const base = Core.aggregateModel(state.model, { documentClass: state.filters.documentClass, sigemStatus: state.filters.sigemStatus, pwStatus: state.filters.pwStatus, discipline: state.filters.discipline, emission: state.filters.emission });
    const sigemComparable = comparableMap(base.documents.sigem);
    const pwComparable = comparableMap(base.documents.pw);
    const sigemNonComparable = nonComparableMap(base.documents.sigem);
    const pwNonComparable = nonComparableMap(base.documents.pw);
    const relation = relationSets(sigemComparable, pwComparable);
    let sigem = sigemComparable;
    let pw = pwComparable;
    if (state.filters.relation === "both") { sigem = subsetMap(sigemComparable, relation.both); pw = subsetMap(pwComparable, relation.both); }
    else if (state.filters.relation === "sigem-only") { sigem = subsetMap(sigemComparable, relation.sigemOnly); pw = new Map(); }
    else if (state.filters.relation === "pw-only") { sigem = new Map(); pw = subsetMap(pwComparable, relation.pwOnly); }
    else if (state.filters.relation === "non-comparable") { sigem = sigemNonComparable; pw = pwNonComparable; }
    const viewSets = relationSets(comparableMap(sigem), comparableMap(pw));
    const emitted = [...pw.values()].filter((document) => document.emitted).length;
    return {
      base, sigem, pw, relation,
      summary: { sigem: sigem.size, pwRegistered: pw.size, pwEmitted: emitted, matched: viewSets.both.size, exclusiveSigem: viewSets.sigemOnly.size, exclusivePw: viewSets.pwOnly.size, coverage: sigem.size ? viewSets.both.size / sigem.size : null, emissionRate: pw.size ? emitted / pw.size : null },
      relationSummary: { matched: relation.both.size, exclusiveSigem: relation.sigemOnly.size, exclusivePw: relation.pwOnly.size, nonComparable: new Set([...sigemNonComparable.keys(), ...pwNonComparable.keys()]).size },
      classes: classRows(comparableMap(sigem), comparableMap(pw)),
      sigemStatus: distribution(sigem, (document) => currentStatus(document, "sigem")),
      pwStatus: distribution(pw, (document) => currentStatus(document, "pw")),
      filterActive: Object.values(state.filters).some(Boolean),
    };
  }

  function ensureStyles() {
    if (document.getElementById("grcon-sigem-pw-dashboard-style-v2")) return;
    const style = document.createElement("style");
    style.id = "grcon-sigem-pw-dashboard-style-v2";
    style.textContent = `
      #${MODULE_ID}{--spw-sigem:#0b7895;--spw-pw:#6d4ac7;--spw-issued:#b16a16;min-width:0}#${MODULE_ID} *{box-sizing:border-box}
      .spw-page-heading{display:flex;align-items:flex-start;justify-content:space-between;gap:16px;margin-bottom:12px}.spw-page-heading h2{margin:0;color:var(--text-strong,#183247);font-size:1.45rem}.spw-page-heading p{max-width:850px;margin:6px 0 0;color:var(--text-muted,#66798a);font-size:.9rem;line-height:1.45}.spw-kicker{display:block;font-size:.67rem;font-weight:900;letter-spacing:.1em;color:var(--brand-700,#155c8a);text-transform:uppercase;margin-bottom:4px}.spw-heading-actions,.spw-base-actions{display:flex;align-items:center;gap:7px;flex-wrap:wrap;justify-content:flex-end}.spw-heading-actions button svg,.spw-base-actions button svg{width:16px;height:16px;fill:none;stroke:currentColor;stroke-width:1.8}.spw-snapshot{padding:6px 9px;border:1px solid var(--border,#dce4eb);border-radius:999px;background:var(--surface,#fff);color:var(--text-muted,#66798a);font-size:.69rem;font-weight:800}
      .spw-progress{display:grid;grid-template-columns:auto 1fr;gap:8px;align-items:center;padding:10px 12px;border-radius:10px;background:var(--brand-50,#eaf5fb);color:var(--brand-800,#0f537a);font-size:.78rem;font-weight:800;margin-bottom:10px}.spw-progress i{width:16px;height:16px;border:2px solid currentColor;border-right-color:transparent;border-radius:50%;animation:spw-spin .7s linear infinite}@keyframes spw-spin{to{transform:rotate(360deg)}}.spw-progress small{grid-column:2;color:var(--text-muted,#66798a);font-weight:600}
      .spw-base-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.spw-base-card,.spw-kpi,.spw-relation,.spw-filter-card,.spw-chart-card,.spw-table-card,.spw-status-card,.spw-quality-card{border:1px solid var(--border,#dce4eb);border-radius:13px;background:var(--surface,#fff);box-shadow:0 5px 18px rgba(32,56,85,.04)}.spw-base-card{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:12px;align-items:center;padding:12px 13px}.spw-base-card span{display:block;font-size:.65rem;font-weight:900;letter-spacing:.08em;color:var(--brand-700,#155c8a)}.spw-base-card strong{display:block;margin-top:4px;color:var(--text-strong,#183247);white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.spw-base-card small,.spw-base-card em{display:block;margin-top:3px;color:var(--text-muted,#66798a);font-size:.7rem}.spw-base-card em{margin-top:6px;font-style:normal;font-weight:800}
      .spw-section-title{display:flex;align-items:flex-end;justify-content:space-between;gap:12px;margin:15px 0 8px}.spw-section-title h3{margin:0;color:var(--text-strong,#183247);font-size:1rem}.spw-section-title p{margin:3px 0 0;color:var(--text-muted,#66798a);font-size:.75rem}.spw-filter-badge{padding:5px 8px;border-radius:999px;background:var(--brand-50,#eaf5fb);color:var(--brand-800,#0f537a);font-size:.69rem;font-weight:900}
      .spw-kpis{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:9px}.spw-kpi{position:relative;overflow:hidden;min-height:102px;padding:12px 13px}.spw-kpi:before{content:"";position:absolute;left:0;top:0;bottom:0;width:4px;background:var(--brand-500,#2789b6)}.spw-kpi.sigem:before{background:var(--spw-sigem)}.spw-kpi.pw:before{background:var(--spw-pw)}.spw-kpi.issued:before{background:var(--spw-issued)}.spw-kpi.coverage:before{background:var(--success-500,#3f8f68)}.spw-kpi span{font-size:.67rem;font-weight:900;text-transform:uppercase;color:var(--text-muted,#687b8c)}.spw-kpi strong{display:block;margin-top:8px;font-size:1.5rem;color:var(--text-strong,#17324a)}.spw-kpi strong.empty{font-size:1.02rem}.spw-kpi small{display:block;margin-top:7px;color:var(--text-muted,#66798a);font-size:.71rem;line-height:1.35}
      .spw-relations{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:9px}.spw-relation{appearance:none;width:100%;text-align:left;padding:13px;color:inherit;cursor:pointer}.spw-relation:hover{border-color:var(--brand-300,#8ac4df)}.spw-relation-top{display:flex;justify-content:space-between;gap:8px}.spw-relation strong{font-size:1.45rem;color:var(--text-strong,#17324a)}.spw-relation b{display:block;margin-top:5px;font-size:.82rem;color:var(--text-strong,#294258)}.spw-relation small{display:block;margin-top:4px;color:var(--text-muted,#66798a);font-size:.71rem}.spw-info{display:inline-grid;place-items:center;width:20px;height:20px;border-radius:50%;border:1px solid var(--border,#d7e0e8);font-size:.7rem;color:var(--text-muted,#66798a)}.spw-link{display:inline-block;margin-top:8px;color:var(--brand-700,#155c8a);font-size:.7rem;font-weight:900}.spw-executive{display:flex;gap:8px;align-items:flex-start;margin:9px 0 0;padding:10px 12px;border:1px solid var(--border,#dce4eb);border-radius:10px;background:var(--surface-soft,#f7fafc);color:var(--text-muted,#5f7385);font-size:.77rem}.spw-executive:before{content:"↗";font-weight:900;color:var(--brand-700,#155c8a)}
      .spw-filter-card{display:grid;grid-template-columns:repeat(6,minmax(130px,1fr)) auto;gap:8px;align-items:end;padding:12px;margin-top:10px}.spw-filter-card label{display:grid;gap:5px}.spw-filter-card label span{font-size:.64rem;font-weight:900;text-transform:uppercase;color:var(--text-muted,#66798a)}.spw-filter-card select{min-height:38px}.spw-filter-note{grid-column:1/-1;color:var(--text-muted,#66798a);font-size:.7rem}
      .spw-chart-card,.spw-table-card,.spw-quality-card{margin-top:10px;overflow:hidden}.spw-card-head{display:flex;align-items:flex-start;justify-content:space-between;gap:12px;padding:13px 14px 9px}.spw-card-head strong{display:block;color:var(--text-strong,#183247);font-size:.95rem}.spw-card-head small{display:block;margin-top:4px;color:var(--text-muted,#66798a);font-size:.72rem}.spw-legend{display:flex;gap:6px;flex-wrap:wrap}.spw-legend button{display:inline-flex;align-items:center;gap:6px;padding:5px 8px;border:1px solid var(--border,#d7e0e8);border-radius:999px;background:var(--surface-soft,#f8fafc);font-size:.7rem;font-weight:900;cursor:help}.spw-legend button:before{content:"";width:9px;height:9px;border-radius:3px;background:currentColor}.spw-legend .sigem{color:var(--spw-sigem)}.spw-legend .pw{color:var(--spw-pw)}.spw-legend .issued{color:var(--spw-issued)}.spw-chart-wrap{padding:0 8px 6px;min-height:270px}.spw-chart-wrap svg{display:block;width:100%;height:300px}.spw-grid-line{stroke:rgba(93,116,136,.14)}.spw-axis-line{stroke:rgba(93,116,136,.36)}.spw-axis-label{fill:var(--text-muted,#6d7f8f);font-size:11px}.spw-total-value{fill:var(--text-strong,#233d52);font-size:11px;font-weight:900;paint-order:stroke;stroke:var(--surface,#fff);stroke-width:3px}.spw-bar-sigem{fill:var(--spw-sigem)}.spw-bar-pw{fill:var(--spw-pw)}.spw-bar-issued{fill:var(--spw-issued)}.spw-small-mark{stroke-width:3;stroke-linecap:round}
      .spw-table-wrap{max-height:360px;overflow:auto;border-top:1px solid var(--border,#e6ebef)}.spw-table-wrap table,.spw-drawer-table table{width:100%;border-collapse:collapse;font-size:.76rem}.spw-table-wrap th,.spw-table-wrap td,.spw-drawer-table th,.spw-drawer-table td{padding:8px 9px;border-bottom:1px solid var(--border,#edf1f4);white-space:nowrap}.spw-table-wrap th,.spw-table-wrap td{text-align:right}.spw-table-wrap th:first-child,.spw-table-wrap td:first-child{text-align:left}.spw-table-wrap thead th,.spw-drawer-table thead th{position:sticky;top:0;z-index:1;background:var(--surface-soft,#f6f9fb);font-size:.62rem;text-transform:uppercase;color:var(--text-muted,#66798a)}.spw-table-wrap button{border:0;background:transparent;color:var(--brand-700,#155c8a);font-weight:900;cursor:pointer}
      .spw-lower-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:10px}.spw-status-list{display:grid;gap:8px;padding:2px 14px 14px}.spw-status-row{display:grid;grid-template-columns:minmax(140px,1fr) minmax(80px,2fr) 54px;gap:9px;align-items:center}.spw-status-row span{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:.74rem;font-weight:800}.spw-status-track{height:8px;border-radius:999px;background:var(--surface-soft,#eef3f6);overflow:hidden}.spw-status-track i{display:block;height:100%;background:var(--brand-500,#2789b6)}.spw-status-row strong{text-align:right;font-size:.74rem}.spw-quality-card{padding:13px}.spw-quality-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:8px;margin-top:8px}.spw-quality-grid div{padding:9px;border-radius:9px;background:var(--surface-soft,#f6f9fb)}.spw-quality-grid span{display:block;font-size:.62rem;font-weight:900;text-transform:uppercase;color:var(--text-muted,#66798a)}.spw-quality-grid strong{display:block;margin-top:4px}.spw-rule{margin:9px 0 0;padding-top:9px;border-top:1px solid var(--border,#e6ebef);color:var(--text-muted,#66798a);font-size:.72rem;line-height:1.45}.spw-empty{display:grid;place-items:center;text-align:center;min-height:170px;color:var(--text-muted,#687b8c)}
      .spw-overlay{position:fixed;inset:0;z-index:1200;background:rgba(22,38,52,.35);display:flex;justify-content:flex-end}.spw-overlay[hidden]{display:none}.spw-drawer{width:min(920px,92vw);height:100%;overflow:auto;background:var(--surface,#fff);box-shadow:-12px 0 32px rgba(13,31,47,.18);padding:16px}.spw-help{width:min(620px,92vw)}.spw-drawer-head{display:flex;align-items:flex-start;justify-content:space-between;gap:12px;padding-bottom:12px;border-bottom:1px solid var(--border,#e1e7ec)}.spw-drawer-head h3{margin:0}.spw-drawer-head p{margin:5px 0 0;color:var(--text-muted,#66798a);font-size:.76rem}.spw-close{border:1px solid var(--border,#d7e0e8);background:var(--surface,#fff);border-radius:8px;min-width:36px;height:36px;cursor:pointer}.spw-drawer-toolbar{display:grid;grid-template-columns:minmax(210px,1.4fr) repeat(4,minmax(120px,1fr)) auto;gap:8px;align-items:end;padding:12px 0}.spw-drawer-toolbar label{display:grid;gap:4px}.spw-drawer-toolbar label span{font-size:.62rem;font-weight:900;text-transform:uppercase;color:var(--text-muted,#66798a)}.spw-drawer-toolbar input,.spw-drawer-toolbar select{min-height:38px}.spw-drawer-table{overflow:auto;border:1px solid var(--border,#e1e7ec);border-radius:10px;max-height:calc(100vh - 205px)}.spw-drawer-table th,.spw-drawer-table td{text-align:left}.spw-reason{white-space:normal!important;min-width:220px;max-width:350px;color:var(--text-muted,#5f7385);line-height:1.35}.spw-chip{display:inline-flex;padding:3px 6px;border-radius:999px;background:var(--surface-soft,#eef3f6);font-size:.64rem;font-weight:900}.spw-help-grid{display:grid;gap:8px;margin-top:12px}.spw-help-grid div{padding:10px;border-radius:9px;background:var(--surface-soft,#f6f9fb)}.spw-help-grid strong{display:block;font-size:.79rem}.spw-help-grid p{margin:3px 0 0;color:var(--text-muted,#66798a);font-size:.74rem;line-height:1.4}
      @media(max-width:1250px){.spw-filter-card{grid-template-columns:repeat(3,minmax(150px,1fr))}.spw-kpis{grid-template-columns:repeat(2,minmax(0,1fr))}.spw-quality-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.spw-drawer-toolbar{grid-template-columns:1fr 1fr 1fr}}
      @media(max-width:850px){.spw-page-heading{display:grid}.spw-heading-actions{justify-content:flex-start}.spw-base-grid,.spw-lower-grid,.spw-relations{grid-template-columns:1fr}.spw-filter-card{grid-template-columns:1fr 1fr}.spw-chart-wrap{overflow-x:auto}.spw-chart-wrap svg{min-width:720px}.spw-drawer{width:100vw}.spw-drawer-toolbar{grid-template-columns:1fr 1fr}}
      @media(max-width:560px){.spw-kpis,.spw-filter-card,.spw-quality-grid,.spw-drawer-toolbar{grid-template-columns:1fr}.spw-base-card{grid-template-columns:1fr}.spw-base-actions{justify-content:flex-start}.spw-card-head{flex-direction:column}}
    `;
    document.head.appendChild(style);
  }

  function createShell() {
    ensureStyles();
    shell = document.getElementById(MODULE_ID);
    if (!shell) { shell = document.createElement("section"); shell.id = MODULE_ID; shell.className = "module-view"; shell.hidden = true; document.querySelector("main.workspace")?.appendChild(shell); }
    shell.setAttribute("role", "tabpanel");
    shell.setAttribute("aria-label", "Dashboard SIGEM × ProjectWise");
    shell.innerHTML = `
      <header class="spw-page-heading"><div><span class="spw-kicker">CONTROLE DOCUMENTAL INTEGRADO</span><h2>Dashboard SIGEM × ProjectWise</h2><p>Veja o universo documental do SIGEM, a cobertura no ProjectWise e os documentos que precisam de investigação — sem depender de conhecimento prévio do processo.</p></div><div class="spw-heading-actions"><span class="spw-snapshot" id="spw-snapshot">Indicadores baseados nos arquivos atualmente carregados</span><button class="secondary-button" id="spw-help-open" type="button">${icon("M12 17v.01M9.6 9a2.5 2.5 0 1 1 4.2 1.82c-.9.74-1.8 1.23-1.8 2.68M12 2a10 10 0 1 0 0 20 10 10 0 0 0 0-20")}<span>Como interpretar</span></button></div></header>
      <div class="spw-progress" id="spw-progress" hidden><i></i><span id="spw-progress-title">Processando base…</span><small id="spw-progress-note">Aguarde a conclusão da etapa atual.</small></div>
      <section class="spw-base-grid"><article class="spw-base-card"><div id="spw-sigem-base"></div><div class="spw-base-actions"><button class="secondary-button" id="spw-sigem-update" type="button">${icon("M12 3v12M8 7l4-4 4 4M5 14v5h14v-5")}<span>Atualizar Consulta Geral</span></button><input id="spw-sigem-file" hidden type="file" accept=".xlsx,.xls,.xlsm"/></div></article><article class="spw-base-card"><div id="spw-pw-base"></div><div class="spw-base-actions"><button class="secondary-button" id="spw-pw-update" type="button">${icon("M12 3v12M8 7l4-4 4 4M5 14v5h14v-5")}<span>Atualizar base PW</span></button><input id="spw-pw-file" hidden type="file" accept=".csv,.txt,text/csv"/></div></article></section>
      <div class="spw-section-title"><div><span class="spw-kicker">VISÃO GERAL</span><h3>Estado da integração documental</h3><p>Totais de documentos únicos e comparáveis.</p></div><span class="spw-filter-badge" id="spw-filter-badge" hidden>Filtro ativo</span></div><section class="spw-kpis" id="spw-kpis"></section>
      <div class="spw-section-title"><div><span class="spw-kicker">COMO AS BASES SE RELACIONAM</span><h3>Relação SIGEM × ProjectWise</h3><p>Os grupos abaixo usam correspondência documental válida; não são diferenças por subtração simples.</p></div></div><section class="spw-relations" id="spw-relations"></section><p class="spw-executive" id="spw-executive"></p>
      <section class="spw-filter-card"><label><span>Classe documental</span><select id="spw-class"><option value="">Todas</option></select></label><label><span>Status SIGEM</span><select id="spw-sigem-status"><option value="">Todos</option></select></label><label><span>Status PW</span><select id="spw-pw-status"><option value="">Todos</option></select></label><label><span>Disciplina PW</span><select id="spw-discipline"><option value="">Todas</option></select></label><label><span>Emissão PW</span><select id="spw-emission"><option value="">Todos</option><option value="emitted">Emitidos</option><option value="not-emitted">Não emitidos</option></select></label><label><span>Situação entre bases</span><select id="spw-relation"><option value="">Todas</option><option value="both">Presente nas duas</option><option value="sigem-only">Exclusivo SIGEM</option><option value="pw-only">Exclusivo PW</option><option value="non-comparable">Não comparável</option></select></label><button class="text-button" id="spw-clear" type="button">Limpar filtros</button><small class="spw-filter-note">Filtros atualizam cards, gráfico e tabela. “Exclusivo” nunca é calculado por subtração cega.</small></section>
      <section class="spw-chart-card"><header class="spw-card-head"><div><span class="spw-kicker">COMPARAÇÃO POR CLASSE</span><strong>Documentos por Classe — SIGEM × ProjectWise</strong><small>Compare quantos existem no SIGEM, quantos estão cadastrados no PW e quantos já possuem evidência de emissão.</small></div><div class="spw-legend"><button class="sigem" type="button" title="Documentos existentes na Consulta Geral do SIGEM.">SIGEM ⓘ</button><button class="pw" type="button" title="Documentos encontrados na base do ProjectWise, independentemente de emissão.">PW Cadastrado ⓘ</button><button class="issued" type="button" title="Documentos cadastrados no PW que atendem à regra de emissão.">PW Emitido ⓘ</button></div></header><div class="spw-chart-wrap" id="spw-chart"></div></section>
      <section class="spw-table-card"><header class="spw-card-head"><div><span class="spw-kicker">NÚMEROS EXATOS</span><strong>Comparação por classe</strong><small>Mesmos conjuntos usados nos cards e no gráfico.</small></div></header><div class="spw-table-wrap" id="spw-table"></div></section>
      <section class="spw-lower-grid"><article class="spw-status-card"><header class="spw-card-head"><div><span class="spw-kicker">SIGEM</span><strong>Status atual por documento</strong><small>Última revisão identificada na Consulta Geral</small></div></header><div class="spw-status-list" id="spw-sigem-status-list"></div></article><article class="spw-status-card"><header class="spw-card-head"><div><span class="spw-kicker">PROJECTWISE</span><strong>Estado atual por documento</strong><small>Estado da revisão mais relevante na base PW</small></div></header><div class="spw-status-list" id="spw-pw-status-list"></div></article></section>
      <section class="spw-quality-card"><span class="spw-kicker">QUALIDADE DA BASE</span><strong>Registros processados e itens que exigem atenção técnica</strong><div class="spw-quality-grid" id="spw-quality"></div><p class="spw-rule" id="spw-rule"></p></section>
      <div class="spw-overlay" id="spw-drill-overlay" hidden><aside class="spw-drawer" role="dialog" aria-modal="true" aria-labelledby="spw-drill-title"><header class="spw-drawer-head"><div><span class="spw-kicker">DETALHAMENTO</span><h3 id="spw-drill-title">Documentos</h3><p id="spw-drill-subtitle"></p></div><button class="spw-close" id="spw-drill-close" type="button" aria-label="Fechar">×</button></header><div class="spw-drawer-toolbar"><label><span>Pesquisar código</span><input id="spw-drill-search" type="search" placeholder="Pesquisar código..."/></label><label><span>Classe</span><select id="spw-drill-class"><option value="">Todas</option></select></label><label><span>Disciplina</span><select id="spw-drill-discipline"><option value="">Todas</option></select></label><label><span>Status</span><select id="spw-drill-status"><option value="">Todos</option></select></label><label><span>Emissão</span><select id="spw-drill-emission"><option value="">Todos</option><option value="yes">Emitidos</option><option value="no">Não emitidos</option></select></label><button class="secondary-button" id="spw-drill-export" type="button">Exportar lista</button></div><div class="spw-drawer-table" id="spw-drill-table"></div></aside></div>
      <div class="spw-overlay" id="spw-help-overlay" hidden><aside class="spw-drawer spw-help" role="dialog" aria-modal="true" aria-labelledby="spw-help-title"><header class="spw-drawer-head"><div><span class="spw-kicker">AJUDA RÁPIDA</span><h3 id="spw-help-title">Como interpretar este Dashboard?</h3><p>Os indicadores refletem os arquivos SIGEM e PW atualmente carregados no GRCON; não são dados em tempo real.</p></div><button class="spw-close" id="spw-help-close" type="button">×</button></header><div class="spw-help-grid"><div><strong>SIGEM</strong><p>Base oficial utilizada para saber quais documentos constam atualmente na Consulta Geral.</p></div><div><strong>PW cadastrado</strong><p>O documento existe como registro no ProjectWise, independentemente de emissão.</p></div><div><strong>PW emitido</strong><p>Além de estar cadastrado, existe evidência na base PW de que o documento passou pelo critério de emissão adotado pelo módulo.</p></div><div><strong>Presentes nas duas bases</strong><p>O GRCON encontrou correspondência documental válida entre SIGEM e ProjectWise.</p></div><div><strong>Exclusivos do SIGEM</strong><p>Existem no SIGEM, mas não possuem correspondência válida na base PW atualmente carregada.</p></div><div><strong>Exclusivos do PW</strong><p>Existem no PW, mas não possuem correspondência válida na Consulta Geral do SIGEM atualmente carregada. Isso não significa automaticamente erro, duplicidade ou necessidade de exclusão.</p></div><div><strong>Não comparáveis</strong><p>Registros cuja identidade não pode ser classificada com segurança como ET, N-1710 ou CV ficam separados dos exclusivos.</p></div></div></aside></div>`;
    bind();
    return shell;
  }

  function el(id) { return shell?.querySelector(`#${id}`); }
  function openOverlay(id) { const overlay = el(id); if (overlay) { overlay.hidden = false; root.setTimeout(() => overlay.querySelector("button,input,select")?.focus(), 0); } }
  function closeOverlay(id) { const overlay = el(id); if (overlay) overlay.hidden = true; }

  function bind() {
    el("spw-sigem-update")?.addEventListener("click", () => el("spw-sigem-file")?.click());
    el("spw-pw-update")?.addEventListener("click", () => el("spw-pw-file")?.click());
    el("spw-sigem-file")?.addEventListener("change", (event) => { const file = event.target.files?.[0]; event.target.value = ""; if (file) void importSigem(file); });
    el("spw-pw-file")?.addEventListener("change", (event) => { const file = event.target.files?.[0]; event.target.value = ""; if (file) void importPw(file); });
    const bindings = { "spw-class": "documentClass", "spw-sigem-status": "sigemStatus", "spw-pw-status": "pwStatus", "spw-discipline": "discipline", "spw-emission": "emission", "spw-relation": "relation" };
    Object.entries(bindings).forEach(([id, field]) => el(id)?.addEventListener("change", () => { state.filters[field] = el(id).value; renderFromModel(false); }));
    el("spw-clear")?.addEventListener("click", () => { Object.keys(state.filters).forEach((field) => { state.filters[field] = ""; }); renderFromModel(true); });
    el("spw-help-open")?.addEventListener("click", () => openOverlay("spw-help-overlay"));
    el("spw-help-close")?.addEventListener("click", () => closeOverlay("spw-help-overlay"));
    el("spw-drill-close")?.addEventListener("click", () => closeOverlay("spw-drill-overlay"));
    root.addEventListener("keydown", (event) => { if (event.key === "Escape") { closeOverlay("spw-help-overlay"); closeOverlay("spw-drill-overlay"); } });
    ["spw-drill-search", "spw-drill-class", "spw-drill-discipline", "spw-drill-status", "spw-drill-emission"].forEach((id) => el(id)?.addEventListener(id === "spw-drill-search" ? "input" : "change", () => {
      state.drill.search = el("spw-drill-search").value; state.drill.documentClass = el("spw-drill-class").value; state.drill.discipline = el("spw-drill-discipline").value; state.drill.status = el("spw-drill-status").value; state.drill.emission = el("spw-drill-emission").value; renderDrillTable();
    }));
    el("spw-drill-export")?.addEventListener("click", exportDrillRows);
    shell.addEventListener("click", (event) => { const target = event.target.closest("[data-spw-drill]"); if (target) openDrill(target.getAttribute("data-spw-drill"), target.getAttribute("data-spw-class") || ""); });
  }

  function setBusy(busy, stage, note) {
    state.busy = busy;
    const progress = el("spw-progress");
    if (progress) { progress.hidden = !busy; if (el("spw-progress-title")) el("spw-progress-title").textContent = stage || "Processando base…"; if (el("spw-progress-note")) el("spw-progress-note").textContent = note || "Aguarde a conclusão da etapa atual."; }
    [el("spw-sigem-update"), el("spw-pw-update"), el("spw-clear")].forEach((button) => { if (button) button.disabled = busy; });
  }
  async function yieldFrame() { await new Promise((resolve) => root.requestAnimationFrame ? root.requestAnimationFrame(resolve) : root.setTimeout(resolve, 0)); }
  async function ensureConferenceRuntime() { if (!root.GRCONModuleLoader) throw new Error("Carregador de módulos do GRCON indisponível."); await root.GRCONModuleLoader.ensure("posting_conference_core.js"); return root.GrconPostingConference; }
  function sheetHeaderRows(sheet, limit) {
    const XLSX = root.XLSX; if (!sheet || !sheet["!ref"] || !XLSX?.utils) return [];
    const range = XLSX.utils.decode_range(sheet["!ref"]); const endRow = Math.min(range.e.r, range.s.r + Math.max(1, Number(limit) || 40) - 1); const output = [];
    for (let row = range.s.r; row <= endRow; row += 1) { const values = []; for (let column = range.s.c; column <= range.e.c; column += 1) { const cell = sheet[XLSX.utils.encode_cell({ r: row, c: column })]; values[column - range.s.c] = cell ? text(cell.w !== undefined ? cell.w : cell.v) : ""; } output.push(values); }
    return output;
  }
  function validateSigemWorkbook(workbook, Conference) {
    let best = null; (workbook?.SheetNames || []).forEach((sheetName) => { const detection = Conference.detectColumns(sheetHeaderRows(workbook.Sheets[sheetName], 40), 40); if (detection && (!best || detection.score > best.score)) best = detection; });
    if (!best) throw new Error("Consulta Geral inválida: não foi possível localizar Documento e Revisão nas primeiras linhas.");
    const missing = ["document", "revision", "status", "documentType"].filter((field) => best.columns[field] < 0); if (missing.length) throw new Error("Consulta Geral inválida: faltam campos obrigatórios. A base vigente foi preservada.");
  }
  async function importSigem(file) {
    setBusy(true, "Lendo arquivo SIGEM...", "Preparando a Consulta Geral."); await yieldFrame();
    try {
      await root.GRCONModuleLoader.ensure("xlsx"); const Conference = await ensureConferenceRuntime(); const buffer = await file.arrayBuffer(); setBusy(true, "Validando dados...", "Conferindo cabeçalhos e estrutura da Consulta Geral."); const workbook = root.XLSX.read(buffer, { type: "array", cellDates: false, dense: false }); validateSigemWorkbook(workbook, Conference); const importedAt = new Date().toISOString(); setBusy(true, "Comparando SIGEM × PW...", "Atualizando a base oficial usada pela Conferência."); const result = await Conference.importWorkbook(workbook, { fileName: file.name, fileSize: file.size, lastModified: file.lastModified, importedAt }, root.GrconHistory?.read?.() || [], { now: importedAt, reason: "sigem-pw-dashboard" }); state.sigem = { meta: result.parsed.meta, records: result.parsed.records }; setBusy(true, "Atualizando dashboard...", "Recalculando indicadores e relações entre as bases."); rebuildModel(); root.dispatchEvent(new CustomEvent("grcon:conference-updated", { detail: { summary: result.summary, changes: result.changes, baseMeta: result.parsed.meta, source: "sigem-pw-dashboard" } })); notify(`Consulta Geral atualizada: ${fmt(result.parsed.meta.recordCount)} registros processados.`, "success"); renderFromModel(true);
    } catch (error) { console.error("[SIGEM×PW] Consulta Geral:", error); notify(error.message || "Não foi possível atualizar a Consulta Geral. A última base válida foi mantida.", "error"); } finally { setBusy(false); }
  }
  async function parsePwFile(file, fileMeta) {
    if (typeof Worker === "undefined") return Core.parsePwCsv(await file.text(), fileMeta);
    const buffer = await file.arrayBuffer();
    return new Promise((resolve, reject) => { let worker; try { worker = new Worker(new URL("workers/sigem_pw_dashboard.worker.js", document.baseURI)); } catch (error) { reject(error); return; } const cleanup = () => worker.terminate(); worker.addEventListener("message", (event) => { const payload = event.data || {}; cleanup(); if (payload.ok && payload.parsed) resolve(payload.parsed); else reject(new Error(payload.error || "Falha ao processar a base ProjectWise.")); }, { once: true }); worker.addEventListener("error", (event) => { cleanup(); reject(event.error || new Error(event.message || "Worker da base ProjectWise falhou.")); }, { once: true }); worker.postMessage({ buffer, meta: fileMeta }, [buffer]); }).catch(async (error) => { console.warn("[SIGEM×PW] Worker PW indisponível; usando processamento local:", error); return Core.parsePwCsv(await file.text(), fileMeta); });
  }
  async function importPw(file) {
    setBusy(true, "Lendo arquivo ProjectWise...", "O CSV será processado sem bloquear a interface."); await yieldFrame();
    try {
      if (!/\.(?:csv|txt)$/i.test(file.name || "")) throw new Error("A relação ProjectWise deve ser fornecida em CSV. A última base válida foi mantida."); const importedAt = new Date().toISOString(); const parsed = await parsePwFile(file, { fileName: file.name, fileSize: file.size, lastModified: file.lastModified, importedAt }); setBusy(true, "Validando dados...", "Conferindo documentos, revisões, estados e evidências de emissão."); const validatedModel = Core.createModel([], parsed.records); parsed.meta.uniqueDocumentCount = validatedModel.pwAll.size; parsed.meta.emittedDocumentCount = [...validatedModel.pwAll.values()].filter((document) => document.emitted).length; const base = { meta: parsed.meta, records: validatedModel.normalizedPw }; setBusy(true, "Comparando SIGEM × PW...", "Aplicando a identidade documental do GRCON."); await Core.savePwBase(base); state.pw = base; rebuildModel(); setBusy(true, "Atualizando dashboard...", "Gerando indicadores, gráfico e listas de investigação."); root.dispatchEvent(new CustomEvent("grcon:pw-base-updated", { detail: { baseMeta: parsed.meta, source: "sigem-pw-dashboard" } })); notify(`Base PW atualizada: ${fmt(parsed.meta.sourceRowCount)} registros brutos · ${fmt(parsed.meta.uniqueDocumentCount)} documentos únicos.`, "success"); renderFromModel(true);
    } catch (error) { console.error("[SIGEM×PW] ProjectWise:", error); notify(error.message || "Não foi possível salvar a nova base do ProjectWise. A base anterior foi preservada.", "error"); } finally { setBusy(false); }
  }
  function rebuildModel() { state.model = Core.createModel(state.sigem.records || [], state.pw.records || []); }
  function optionHtml(value, label) { return `<option value="${escapeHtml(value)}">${escapeHtml(label || value)}</option>`; }
  function syncSelect(id, values, current, allLabel) { const select = el(id); if (!select) return; const list = [...new Set((values || []).filter(Boolean))]; select.innerHTML = optionHtml("", allLabel) + list.map((value) => optionHtml(value)).join(""); select.value = list.includes(current) ? current : ""; }
  function renderFilters(view) {
    const base = view.base; syncSelect("spw-class", MACRO_CLASSES.filter((value) => base.filterOptions.classes.includes(value)), state.filters.documentClass, "Todas"); syncSelect("spw-sigem-status", base.filterOptions.sigemStatuses, state.filters.sigemStatus, "Todos"); syncSelect("spw-pw-status", base.filterOptions.pwStatuses, state.filters.pwStatus, "Todos"); syncSelect("spw-discipline", base.filterOptions.disciplines, state.filters.discipline, "Todas"); el("spw-emission").value = state.filters.emission; el("spw-relation").value = state.filters.relation;
    const badge = el("spw-filter-badge"); badge.hidden = !view.filterActive; if (!badge.hidden) { const labels = []; if (state.filters.documentClass) labels.push(state.filters.documentClass); if (state.filters.relation) labels.push(RELATION_LABELS[state.filters.relation] || state.filters.relation); badge.textContent = `Filtro ativo: ${labels.join(" · ") || "critérios adicionais"}`; }
  }
  function renderBaseCards(view) {
    const sigemMeta = state.sigem.meta, pwMeta = state.pw.meta, q = view.base.quality || {};
    el("spw-sigem-base").innerHTML = sigemMeta ? `<span>BASE SIGEM · CONSULTA GERAL</span><strong title="${escapeHtml(sigemMeta.fileName)}">${escapeHtml(sigemMeta.fileName || "Consulta Geral")}</strong><small>Última atualização: ${fmtDate(sigemMeta.importedAt)}</small><em>${fmt(sigemMeta.recordCount)} registros/revisões · ${fmt(q.sigemUniqueDocuments)} documentos únicos</em>` : `<span>BASE SIGEM</span><strong>Consulta Geral não carregada</strong><small>Use “Atualizar Consulta Geral”.</small><em>Base ausente não é zero.</em>`;
    el("spw-pw-base").innerHTML = pwMeta ? `<span>BASE PROJECTWISE</span><strong title="${escapeHtml(pwMeta.fileName)}">${escapeHtml(pwMeta.fileName || "Relação PW")}</strong><small>Última atualização: ${fmtDate(pwMeta.importedAt)}</small><em>${fmt(pwMeta.sourceRowCount)} registros brutos · ${fmt(q.pwUniqueDocuments)} documentos únicos</em>` : `<span>BASE PROJECTWISE</span><strong>Base ProjectWise não carregada</strong><small>Use “Atualizar base PW”.</small><em>Base ausente não é zero.</em>`;
    el("spw-snapshot").textContent = sigemMeta || pwMeta ? `SIGEM: ${fmtDate(sigemMeta?.importedAt)} · PW: ${fmtDate(pwMeta?.importedAt)}` : "Indicadores baseados nos arquivos atualmente carregados";
  }
  function kpi(label, value, css, note, available) { return `<article class="spw-kpi ${css}"><span>${escapeHtml(label)}</span><strong class="${available ? "" : "empty"}">${available ? escapeHtml(value) : "Base não carregada"}</strong><small>${escapeHtml(note || "")}</small></article>`; }
  function renderKpis(view) {
    const s = view.summary, hasSigem = Boolean(state.sigem.meta), hasPw = Boolean(state.pw.meta);
    el("spw-kpis").innerHTML = [kpi("Total SIGEM", fmt(s.sigem), "sigem", "Documentos únicos comparáveis no filtro atual", hasSigem), kpi("PW cadastrado", fmt(s.pwRegistered), "pw", "Documentos únicos registrados no ProjectWise", hasPw), kpi("PW emitido", fmt(s.pwEmitted), "issued", hasPw ? `${pct(s.pwEmitted, s.pwRegistered)} dos cadastrados no PW` : "Aguardando base PW", hasPw), kpi("Cobertura no PW", s.coverage === null ? "—" : pct(s.matched, s.sigem), "coverage", hasSigem && hasPw ? `${fmt(s.matched)} dos ${fmt(s.sigem)} documentos SIGEM também foram encontrados no PW` : "Requer as duas bases", hasSigem && hasPw)].join("");
  }
  function relationCard(kind, value, title, subtitle, tooltip) { return `<button class="spw-relation" type="button" data-spw-drill="${kind}"><span class="spw-relation-top"><strong>${fmt(value)}</strong><span class="spw-info" title="${escapeHtml(tooltip)}">ⓘ</span></span><b>${escapeHtml(title)}</b><small>${escapeHtml(subtitle)}</small><span class="spw-link">Ver documentos →</span></button>`; }
  function renderRelations(view) {
    const r = view.relationSummary;
    el("spw-relations").innerHTML = [relationCard("both", r.matched, "Presentes nas duas bases", "Correspondência SIGEM × PW", "Documentos com correspondência documental válida nas duas bases."), relationCard("sigem-only", r.exclusiveSigem, "Exclusivos do SIGEM", "Não localizados no PW", "Documentos válidos e comparáveis do SIGEM sem correspondência válida no ProjectWise."), relationCard("pw-only", r.exclusivePw, "Exclusivos do PW", "Sem correspondência no SIGEM", "Documentos do ProjectWise sem correspondência válida na Consulta Geral atual. Isso não significa automaticamente erro, duplicidade ou necessidade de exclusão.")].join("");
    const max = Math.max(r.matched, r.exclusiveSigem, r.exclusivePw); const phrase = max === r.exclusiveSigem ? "A maior diferença atual está nos documentos exclusivos do SIGEM. Consulte os detalhes para identificar quais classes concentram essa diferença." : max === r.exclusivePw ? "A maior diferença atual está nos documentos exclusivos do PW. Isso não significa automaticamente erro; use o detalhamento para entender o grupo." : "A maior parcela dos documentos comparáveis está presente nas duas bases. Use o detalhamento para investigar as diferenças restantes."; el("spw-executive").textContent = `${phrase}${r.nonComparable ? ` Há ${fmt(r.nonComparable)} documento(s) não comparável(is), separados dos exclusivos.` : ""}`;
  }
  function niceMaximum(value) { const padded = Math.max(1, Number(value) || 0) * 1.12; const magnitude = 10 ** Math.floor(Math.log10(padded)); const normalized = padded / magnitude; return (normalized <= 1 ? 1 : normalized <= 1.5 ? 1.5 : normalized <= 2 ? 2 : normalized <= 2.5 ? 2.5 : normalized <= 5 ? 5 : 10) * magnitude; }
  function groupedBarSvg(rows) {
    if (!rows?.length) return `<div class="spw-empty"><div><strong>Sem classes para exibir</strong><span>Ajuste os filtros ou carregue uma base.</span></div></div>`;
    const width = 920, height = 300, margin = { top: 36, right: 22, bottom: 50, left: 58 }, plotWidth = width - margin.left - margin.right, plotHeight = height - margin.top - margin.bottom, maximum = niceMaximum(Math.max(...rows.flatMap((row) => [row.sigem, row.pwRegistered, row.pwEmitted]), 1)), slot = plotWidth / rows.length, groupWidth = Math.min(180, slot * .64), gap = Math.max(7, groupWidth * .06), barWidth = Math.max(20, (groupWidth - gap * 2) / 3), y = (value) => margin.top + plotHeight - (Number(value || 0) / maximum) * plotHeight, parts = [];
    [0, .25, .5, .75, 1].forEach((ratio) => { const value = Math.round(maximum * ratio), yy = y(value); parts.push(`<line class="spw-grid-line" x1="${margin.left}" y1="${yy}" x2="${width - margin.right}" y2="${yy}"/><text class="spw-axis-label" text-anchor="end" x="${margin.left - 8}" y="${yy + 4}">${fmt(value)}</text>`); }); parts.push(`<line class="spw-axis-line" x1="${margin.left}" y1="${margin.top + plotHeight}" x2="${width - margin.right}" y2="${margin.top + plotHeight}"/>`);
    rows.forEach((row, index) => { const center = margin.left + slot * index + slot / 2, start = center - groupWidth / 2; [["SIGEM", row.sigem, "spw-bar-sigem", "#0b7895"], ["PW Cadastrado", row.pwRegistered, "spw-bar-pw", "#6d4ac7"], ["PW Emitido", row.pwEmitted, "spw-bar-issued", "#b16a16"]].forEach(([label, value, css, stroke], seriesIndex) => { const x = start + seriesIndex * (barWidth + gap), yy = y(value), h = Math.max(0, margin.top + plotHeight - yy), title = `${row.documentClass} · ${label}: ${fmt(value)} · Cobertura SIGEM→PW: ${pct(row.matched, row.sigem)} · Emissão entre cadastrados: ${pct(row.pwEmitted, row.pwRegistered)} · Exclusivos SIGEM: ${fmt(row.exclusiveSigem)} · Exclusivos PW: ${fmt(row.exclusivePw)}`; if (value > 0 && h < 4) parts.push(`<line class="spw-small-mark" x1="${x}" y1="${margin.top + plotHeight - 3}" x2="${x + barWidth}" y2="${margin.top + plotHeight - 3}" style="stroke:${stroke}"><title>${escapeHtml(title)}</title></line>`); else parts.push(`<rect class="${css}" x="${x}" y="${yy}" width="${barWidth}" height="${h}" rx="3"><title>${escapeHtml(title)}</title></rect>`); if (value > 0) parts.push(`<text class="spw-total-value" text-anchor="middle" x="${x + barWidth / 2 + (seriesIndex === 0 ? -3 : seriesIndex === 2 ? 3 : 0)}" y="${Math.max(14, h < 15 ? margin.top + plotHeight - 8 : yy - 6)}">${fmt(value)}</text>`); }); parts.push(`<text class="spw-axis-label" text-anchor="middle" x="${center}" y="${height - 22}">${escapeHtml(row.documentClass)}</text>`); });
    return `<svg viewBox="0 0 ${width} ${height}" role="img" aria-label="Comparação SIGEM, PW cadastrado e PW emitido por classe">${parts.join("")}</svg>`;
  }
  function renderChart(view) { el("spw-chart").innerHTML = state.sigem.meta || state.pw.meta ? groupedBarSvg(view.classes) : `<div class="spw-empty"><div><strong>Nenhuma base carregada</strong><span>Atualize SIGEM e PW para comparar.</span></div></div>`; }
  function renderTable(view) {
    if (!state.sigem.meta && !state.pw.meta) { el("spw-table").innerHTML = `<div class="spw-empty"><div><strong>Sem dados</strong></div></div>`; return; }
    const body = view.classes.map((row) => `<tr><td><strong>${escapeHtml(row.documentClass)}</strong></td><td>${fmt(row.sigem)}</td><td>${fmt(row.pwRegistered)}</td><td>${fmt(row.pwEmitted)}</td><td>${fmt(row.matched)}</td><td><button type="button" data-spw-drill="sigem-only" data-spw-class="${escapeHtml(row.documentClass)}">${fmt(row.exclusiveSigem)}</button></td><td><button type="button" data-spw-drill="pw-only" data-spw-class="${escapeHtml(row.documentClass)}">${fmt(row.exclusivePw)}</button></td><td>${pct(row.matched, row.sigem)}</td><td>${pct(row.pwEmitted, row.pwRegistered)}</td></tr>`).join(""); el("spw-table").innerHTML = `<table><thead><tr><th>Classe</th><th>SIGEM</th><th>PW cadastrado</th><th>PW emitido</th><th>Nas duas bases</th><th>Exclusivos SIGEM</th><th>Exclusivos PW</th><th>Cobertura</th><th>Emissão PW</th></tr></thead><tbody>${body}</tbody></table>`;
  }
  function statusRows(items, total) { if (!items?.length) return `<div class="spw-empty"><div><strong>Sem status disponível</strong></div></div>`; const max = Math.max(1, ...items.slice(0, 10).map((item) => item.count)); return items.slice(0, 10).map((item) => `<div class="spw-status-row"><span title="${escapeHtml(item.label)}">${escapeHtml(item.label)}</span><div class="spw-status-track"><i style="width:${Math.max(2, item.count / max * 100)}%"></i></div><strong>${fmt(item.count)}</strong></div>`).join("") + (items.length > 10 ? `<small>+ ${fmt(items.length - 10)} situações · ${fmt(total)} documentos</small>` : ""); }
  function renderStatuses(view) { el("spw-sigem-status-list").innerHTML = statusRows(state.sigem.meta ? view.sigemStatus : [], view.summary.sigem); el("spw-pw-status-list").innerHTML = statusRows(state.pw.meta ? view.pwStatus : [], view.summary.pwRegistered); }
  function renderQuality(view) {
    const q = view.base.quality || {}, s = state.sigem.meta || {}, p = state.pw.meta || {}; const cells = [["SIGEM · registros/revisões", state.sigem.meta ? fmt(s.recordCount || q.sigemRawRecords) : "—"], ["SIGEM · documentos únicos", state.sigem.meta ? fmt(q.sigemUniqueDocuments) : "—"], ["PW · registros brutos / válidos", state.pw.meta ? `${fmt(p.sourceRowCount)} / ${fmt(p.recordCount)}` : "—"], ["PW · documentos / emitidos", state.pw.meta ? `${fmt(q.pwUniqueDocuments)} / ${fmt(q.pwEmittedDocuments)}` : "—"], ["PW · linhas ignoradas", state.pw.meta ? fmt(p.invalidCount) : "—"], ["PW · emissão desconhecida", state.pw.meta ? fmt(p.unknownEmissionCount) : "—"], ["Não comparáveis", state.sigem.meta || state.pw.meta ? fmt(view.relationSummary.nonComparable) : "—"], ["Classes comparáveis", "ET · N-1710 · CV"]]; el("spw-quality").innerHTML = cells.map(([label, value]) => `<div><span>${escapeHtml(label)}</span><strong>${escapeHtml(value)}</strong></div>`).join(""); el("spw-rule").textContent = `Regra de emissão PW: ${Core.EMISSION_RULE} EAP diferente continua sendo documento diferente. Itens não comparáveis ficam fora dos conjuntos de exclusividade.`;
  }
  function validateConsistency(view) { const r = view.relationSummary, sigem = comparableMap(view.base.documents.sigem).size, pw = comparableMap(view.base.documents.pw).size; if (r.matched + r.exclusiveSigem !== sigem || r.matched + r.exclusivePw !== pw) console.error("[SIGEM×PW] Inconsistência de conjuntos detectada.", { r, sigem, pw }); }
  function renderFromModel(refreshOptions) { if (!state.model) rebuildModel(); state.result = buildView(); validateConsistency(state.result); renderBaseCards(state.result); renderKpis(state.result); renderRelations(state.result); if (refreshOptions !== false || state.result.filterActive) renderFilters(state.result); renderChart(state.result); renderTable(state.result); renderStatuses(state.result); renderQuality(state.result); }

  function relationSource(relationName) {
    const view = state.result || buildView(), sigem = comparableMap(view.base.documents.sigem), pw = comparableMap(view.base.documents.pw), sets = relationSets(sigem, pw); if (relationName === "both") return { keys: sets.both, sigem, pw }; if (relationName === "sigem-only") return { keys: sets.sigemOnly, sigem, pw }; if (relationName === "pw-only") return { keys: sets.pwOnly, sigem, pw }; const ns = nonComparableMap(view.base.documents.sigem), np = nonComparableMap(view.base.documents.pw); return { keys: new Set([...ns.keys(), ...np.keys()]), sigem: ns, pw: np };
  }
  function exclusivityReason(document, oppositeMap, oppositeLabel) {
    const info = identityInfo(document); if (info?.eapApplicable && info?.irregularities?.length) return info.irregularities[0].message;
    if (info?.family === "ET" && info.tagComparable) { const candidates = [...oppositeMap.values()].map((item) => identityInfo(item)).filter((candidate) => candidate?.family === "ET" && candidate.tagComparable === info.tagComparable); if (candidates.length) { const sameType = candidates.filter((candidate) => norm(candidate.documentType) === norm(info.documentType)); if (sameType.some((candidate) => candidate.eap && info.eap && candidate.eap !== info.eap)) return "TAG equivalente encontrado, porém em EAP diferente. O GRCON trata EAP diferente como documento distinto."; if (!sameType.length) return "TAG equivalente encontrado, porém com tipo documental diferente."; return "Código semelhante localizado, mas sem identidade documental suficiente para correspondência válida."; } }
    return `Nenhum documento correspondente foi localizado ${oppositeLabel}.`;
  }
  function drillRows() {
    const relationName = state.drill.relation, source = relationSource(relationName), rows = [];
    source.keys.forEach((key) => { const sigem = source.sigem.get(key), pw = source.pw.get(key), primary = relationName === "sigem-only" ? sigem : (pw || sigem); if (!primary) return; const current = relationName === "sigem-only" ? sigem?.current : (pw?.current || sigem?.current); let reason = relationName === "both" ? "Correspondência documental válida entre SIGEM e ProjectWise." : relationName === "pw-only" ? exclusivityReason(pw, source.sigem, "na Consulta Geral do SIGEM") : relationName === "sigem-only" ? exclusivityReason(sigem, source.pw, "na base ProjectWise") : identityInfo(primary)?.irregularities?.[0]?.message || "Código fora das famílias documentais comparáveis ET, N-1710 e CV."; rows.push({ document: text(primary.document), documentClass: text(primary.documentClass) || "Não comparável", revision: text(current?.revision || current?.revisionComplete), type: text(current?.documentType || current?.documentTypeDesc), discipline: currentDiscipline(pw || primary), status: relationName === "sigem-only" ? currentStatus(sigem, "sigem") : currentStatus(pw || primary, pw ? "pw" : "sigem"), emitted: Boolean(pw?.emitted), reason }); }); return rows.sort((a, b) => a.document.localeCompare(b.document, "pt-BR", { numeric: true }));
  }
  function filteredDrillRows() { const search = norm(state.drill.search); return drillRows().filter((row) => (!search || norm([row.document, row.revision, row.type, row.discipline, row.status, row.reason].join(" ")).includes(search)) && (!state.drill.documentClass || row.documentClass === state.drill.documentClass) && (!state.drill.discipline || norm(row.discipline) === norm(state.drill.discipline)) && (!state.drill.status || norm(row.status) === norm(state.drill.status)) && (state.drill.emission !== "yes" || row.emitted) && (state.drill.emission !== "no" || !row.emitted)); }
  function openDrill(relationName, documentClass) { state.drill = { relation: relationName, search: "", documentClass: documentClass || "", discipline: "", status: "", emission: "" }; const rows = drillRows(); el("spw-drill-title").textContent = RELATION_LABELS[relationName] || "Documentos"; el("spw-drill-search").value = ""; syncSelect("spw-drill-class", MACRO_CLASSES.filter((value) => rows.some((row) => row.documentClass === value)), state.drill.documentClass, "Todas"); syncSelect("spw-drill-discipline", [...new Set(rows.map((row) => row.discipline).filter(Boolean))].sort(), "", "Todas"); syncSelect("spw-drill-status", [...new Set(rows.map((row) => row.status).filter(Boolean))].sort(), "", "Todos"); el("spw-drill-emission").value = ""; renderDrillTable(); openOverlay("spw-drill-overlay"); }
  function renderDrillTable() { const rows = filteredDrillRows(); el("spw-drill-subtitle").textContent = `${fmt(rows.length)} documento(s) exibido(s).`; const body = rows.map((row) => `<tr><td><strong>${escapeHtml(row.document)}</strong></td><td><span class="spw-chip">${escapeHtml(row.documentClass)}</span></td><td>${escapeHtml(row.revision || "—")}</td><td>${escapeHtml(row.type || "—")}</td><td>${escapeHtml(row.discipline || "—")}</td><td>${escapeHtml(row.status || "—")}</td><td>${row.emitted ? "Sim" : "Não"}</td><td class="spw-reason">${escapeHtml(row.reason)}</td></tr>`).join(""); el("spw-drill-table").innerHTML = `<table><thead><tr><th>Documento</th><th>Classe</th><th>Revisão</th><th>Tipo</th><th>Disciplina PW</th><th>Status</th><th>Emitido?</th><th>Motivo / situação</th></tr></thead><tbody>${body || `<tr><td colspan="8">Nenhum documento corresponde aos filtros.</td></tr>`}</tbody></table>`; }
  function exportDrillRows() { const rows = filteredDrillRows(); if (!rows.length) return notify("Não há documentos para exportar.", "info"); const quote = (value) => `"${text(value).replace(/"/g, '""')}"`; const csv = "\uFEFF" + [["Documento", "Classe", "Revisão", "Tipo", "Disciplina PW", "Status", "Emitido", "Motivo/Situação"], ...rows.map((row) => [row.document, row.documentClass, row.revision, row.type, row.discipline, row.status, row.emitted ? "Sim" : "Não", row.reason])].map((row) => row.map(quote).join(";")).join("\r\n"); const blob = new Blob([csv], { type: "text/csv;charset=utf-8" }); const filename = `GRCON_${(RELATION_LABELS[state.drill.relation] || "documentos").replace(/\s+/g, "_")}_${new Date().toISOString().slice(0, 10)}.csv`; if (root.GrconUtils?.downloadBlob) root.GrconUtils.downloadBlob(blob, filename); }
  async function refreshBases(reason) { if (refreshPromise) return refreshPromise; refreshPromise = (async () => { try { const bases = await Core.loadBases(); state.sigem = bases.sigem?.meta ? bases.sigem : { meta: null, records: [] }; state.pw = bases.pw?.meta ? bases.pw : { meta: null, records: [] }; rebuildModel(); renderFromModel(true); state.ready = true; } catch (error) { console.error(`[SIGEM×PW] atualização ${reason || ""}:`, error); notify(error.message || "Não foi possível ler as bases persistidas.", "error"); } })().finally(() => { refreshPromise = null; }); return refreshPromise; }
  async function activate() { createShell(); shell.hidden = false; if (!state.ready) { setBusy(true, "Carregando bases vigentes...", "Lendo a Consulta Geral e a base ProjectWise persistidas."); await yieldFrame(); await refreshBases("ativação"); setBusy(false); } else renderFromModel(false); }
  root.addEventListener("grcon:conference-updated", (event) => { if (event?.detail?.source !== "sigem-pw-dashboard") void refreshBases("Consulta Geral atualizada em outro módulo"); });
  root.addEventListener("grcon:pw-base-updated", (event) => { if (event?.detail?.source !== "sigem-pw-dashboard") void refreshBases("base PW atualizada em outro módulo"); });
  root.GrconSigemPwDashboardUi = Object.freeze({ activate, refresh: refreshBases, state });
})(window);