const assert = require('node:assert/strict');
const Compliance = require('../documentary_compliance');
const Engine = require('../normative_rule_engine');
const Versions = require('../normative_version_registry');
const Registry = require('../normative_registry');
const History = require('../history_core');
const Emission = require('../emission');
const Reissue = require('../grdt_reissue_core');
const Report = require('../history_report');
const doc = 'RL-5290.00-22313-91B-C1O-002';
const data = { document: doc, revision: 'B', title: 'RELATÓRIO', fileName: `${doc}_0001_B.pdf`, format: 'A4', discipline: 'DINÂMICOS', documentType: 'RL', purpose: 'Para Construção', databook: 'R:\\DB' };
const good = Compliance.audit(data);
assert.equal(good.outcome, 'CONFORME');
assert.equal(good.components.activity, '22313');
assert.equal(good.information.length, 1, 'NORTEC ausente é informação, não confirmação de existência');
assert.ok(good.normsApplied.some(norm => norm.part === 'Anexo D' && norm.revision === 'BG'));
assert.equal(Compliance.audit({ ...data, documentType: 'FD' }).outcome, 'ALERTA');
assert.equal(Compliance.audit({ ...data, document: 'RL-5290.00-22313-ZZZ-C1O-002' }).blocks.length, 0);
assert.equal(Compliance.audit({ document: 'CV-LEGADO', revision: '0', sheet: 'CV' }).outcome, 'NÃO APLICÁVEL');
assert.equal(Compliance.audit({ ...data, action: 'cancel', previouslyEmitted: false }).blocks.length, 0, 'N-2064 com fonte pendente não bloqueia');
const row = { document: doc, revision: 'B', sheet: 'N-1710', egrdt: data, record: { discipline: data.discipline, databook: data.databook }, files: [{ name: data.fileName, finalName: data.fileName, file: { size: 1 } }] };
assert.equal(Compliance.auditRow(row), Compliance.auditRow(row), 'reaproveita a validação sem edição');
const first = Compliance.auditRow(row);
row.egrdt = { ...data, documentType: 'FD' };
assert.notEqual(Compliance.auditRow(row), first, 'edição invalida o cache');
row.egrdt = data;
const plan = Emission.createPlan([row], new Set([0]));
assert.equal(plan.errors.length, 0);
assert.ok(plan.entries[0].normativeValidation.rulesChecked.length > 0);
const record = History.recordFromGenerated({ fileName: 'eGRDT.xls', group: { entries: plan.entries } }, [row], { generatedAt: '2026-10-01T12:00:00Z' });
assert.equal(record.normativeValidation.normativeValidationVersion, Compliance.VERSION);
assert.equal(record.files[0].normativeValidation.results, undefined, 'snapshot compacto evita duplicar conformes');
assert.equal(record.normativeValidation.counts.compliant, record.files[0].normativeValidation.counts.compliant, 'agregação preserva a contagem de regras conformes no snapshot compacto');
assert.deepEqual(History.cleanRecord(record).normativeValidation, record.normativeValidation);
assert.equal(Report.documentRows([record])[0]['VERSÃO DA VALIDAÇÃO NORMATIVA'], Compliance.VERSION);
assert.equal(History.cleanRecord({ ...record, normativeValidation: null, files: [] }).normativeValidation, null, 'não reavalia o passado');
const reissue = Reissue.groupRows([{ item: data, sourceFile: record.files[0], sourceEgrdt: 'ORIGEM' }], 48, 'limit-only');
assert.ok(reissue[0].entries[0].normativeValidation);
const before = JSON.stringify(record.normativeValidation);
Compliance.versions.register({ ...Compliance.versions.get('N-1710', 'body'), revision: 'X', catalogRevision: 'X' }, { replace: true });
assert.notEqual(Compliance.auditRow(row), first, 'mudança da base também invalida o cache');
assert.equal(JSON.stringify(record.normativeValidation), before, 'snapshot histórico não muda ao atualizar a base');
const rule = Registry.normalizeRule({ ruleId: 'test.version', norm: 'N-1710', revision: 'N', section: '5', title: 'Version', description: 'Version', type: 'mandatory', severity: 'block', status: 'active', source: { part: 'body' } });
const versions = Versions.createVersionRegistry([{ norm: 'N-1710', revision: 'X', status: 'active' }]);
const stale = Engine.evaluateRule(rule, {}, () => ({ passed: false }), versions);
assert.equal(stale.outcome, 'ALERTA');
assert.equal(stale.code, 'rule_revision_mismatch');
const matching = Versions.createVersionRegistry([{ norm: 'N-1710', revision: 'N', status: 'active' }]);
assert.equal(Engine.evaluateRule(rule, {}, () => ({}), matching).code, 'evaluation_undetermined');
assert.equal(Engine.evaluateRule(rule, {}, () => { throw Error('unavailable'); }, matching).code, 'evaluator_failed');
assert.equal(Engine.evaluateRule(rule, {}, () => ({ passed: false }), matching).outcome, 'BLOQUEIO');
assert.equal(Engine.evaluateRule(rule, {}, () => ({ passed: true }), matching).overrideAllowed, false);
console.log('documentary_compliance: parser, fonte, aplicabilidade, cache, emissão normal, Repostagem, Histórico e exportação OK.');
