'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {PGlite}=require('@electric-sql/pglite');
const {randomUUID}=require('node:crypto');
const Core=require('../egrdt_teams_trace_core.js');
const root=path.resolve(__dirname,'..'),w=randomUUID(),other=randomUUID(),user=randomUUID(),viewer=randomUUID(),hid=randomUUID(),cid=randomUUID(),tenant=randomUUID();
const number='0130870-C1O-PGV-G-2026-0123 - eGRDT';
(async()=>{
 const db=new PGlite();const originalFetch=global.fetch;
 try{
  await db.exec(`create schema private;create role anon;create role authenticated;create role service_role;
   create table grcon_workspaces(id uuid primary key);
   create table grcon_contracts(id uuid primary key,workspace_id uuid,code text,active boolean);
   create table grcon_memberships(workspace_id uuid,user_id uuid,active boolean,role text);
   create table grcon_history(id uuid primary key,workspace_id uuid,contract_id uuid,client_record_id text,egrdt_number text,deleted_at timestamptz,payload jsonb);
   create table grcon_notifications(id uuid default gen_random_uuid(),workspace_id uuid,contract_id uuid,event_key text unique,kind text,title text,message text,document_code text,link_target text);
   insert into grcon_workspaces values('${w}'),('${other}');
   insert into grcon_contracts values('${cid}','${w}','UHDT-D',true),('${randomUUID()}','${other}','UGH',true);
   insert into grcon_memberships values('${w}','${user}',true,'operator'),('${w}','${viewer}',true,'viewer');`);
  const files=[{document:'DOC-001',grdtRevision:'0',discipline:'CE',purpose:'Construção',sigemStatus:'Em análise'},{document:'DOC-002',revision:'A',discipline:'CE',purpose:'Cancelamento'}];
  const payload={files,egrdtNumber:number};
  await db.query('insert into grcon_history values($1,$2,$3,$4,$5,null,$6)',[hid,w,cid,'client123',number,payload]);
  await db.exec(fs.readFileSync(path.join(root,'supabase/migrations/20261009141012_egrdt_teams_traceability.sql'),'utf8'));
  const rpc=(workspace,actor,operation,input)=>db.query('select grcon_teams_operation($1,$2,$3,$4) data',[workspace,actor,operation,input]).then(r=>r.rows[0].data);
  const id=randomUUID(),start={attemptId:id,historyRecordId:hid,clientRecordId:'client123'};
  let a=(await rpc(w,user,'start',start)).attempt;
  assert.equal(a.documents.length,2);assert.equal(a.documents[0].purpose,'Construção');
  assert.equal((await rpc(w,user,'start',start)).shouldSend,false);
  await assert.rejects(rpc(other,user,'start',start),/acesso/);
  await assert.rejects(rpc(w,viewer,'start',{...start,attemptId:randomUUID()}),/permissão/);
  await assert.rejects(rpc(w,user,'start',{attemptId:randomUUID(),historyRecordId:randomUUID()}),/sincronizada/);
  await assert.rejects(rpc(other,null,'confirm',{attemptId:id}),/encontrada/);
  assert.equal((await rpc(w,viewer,'page',{})).length,1);
  await db.exec('set role authenticated');
  await assert.rejects(rpc(w,user,'page',{}),/permission denied/);
  await assert.rejects(db.query('select * from private.grcon_teams_attempts'),/permission denied/);
  await db.exec('reset role');
  const confirm={attemptId:id,messageId:'card1',conversationId:'chat1',type:'partial',selectedIndices:['0'],responder:{objectId:randomUUID(),displayName:'João Silva',tenantId:tenant}};
  await assert.rejects(rpc(w,null,'confirm',{...confirm,selectedIndices:['999']}),/inválida/);
  await assert.rejects(rpc(w,null,'confirm',{...confirm,selectedIndices:['0','0']}),/inválida/);
  await assert.rejects(rpc(w,null,'confirm',{...confirm,selectedIndices:['0','1']}),/inválida/);
  const results=await Promise.all([rpc(w,null,'confirm',confirm),rpc(w,null,'confirm',confirm)]);
  assert.equal(results.filter(r=>r.duplicate).length,1);
  const noticeClaims=await Promise.all([rpc(w,null,'claim_notice',{attemptId:id}),rpc(w,null,'claim_notice',{attemptId:id})]);
  assert.equal(noticeClaims.filter(r=>r.publishConfirmation).length,1,'one flow claims the external announcement');
  assert.equal(results.filter(r=>r.duplicate).length,1);
  a=results[0].attempt;
  assert.equal(a.confirmation_type,'partial');assert.equal(a.confirmed_documents.length,1);
  assert.equal((await db.query('select count(*)::int n from grcon_notifications')).rows[0].n,1);
  await rpc(w,null,'failed',{attemptId:id});
  assert.equal((await rpc(w,user,'detail',{attemptId:id})).attempt.delivery_status,'delivered','late failures never overwrite confirmed delivery');
  await assert.rejects(rpc(w,null,'confirm',{...confirm,messageId:'wrong'}),/corresponde/);
  assert.deepEqual((await db.query('select payload from grcon_history where id=$1',[hid])).rows[0].payload,payload,'official SIGEM data never changed');
  const newId=randomUUID();await rpc(w,user,'start',{...start,attemptId:newId});
  const total=await rpc(w,null,'confirm',{...confirm,attemptId:newId,messageId:'card2',type:'total'});
  assert.equal(total.attempt.confirmed_documents.length,2,'resend has an independent identity');
  const expired=randomUUID();await rpc(w,user,'start',{...start,attemptId:expired});
  await db.query("update private.grcon_teams_attempts set expires_at=now()-interval '1 day' where id=$1",[expired]);
  await assert.rejects(rpc(w,null,'confirm',{...confirm,attemptId:expired}),/expirado/);
  const map=Core.index([a,total.attempt]);
  assert.equal(Core.attemptsFor({workspaceId:other,cloudId:hid},map).length,0);
  assert.equal(Core.values(null)[0],'Sem registro de envio ao Teams');assert.equal(Core.values(null)[2],'Não informado');
  assert.equal(Core.confirmed(a,files[0]),'Sim');assert.equal(Core.confirmed(a,files[1]),'Não');
  assert.match(Core.conference({document:'DOC-001',revisionSent:'0',status:'NAO_ENCONTRADO'},a),/ainda não confirmado/);
  assert.equal(Core.conference({document:'DOC-001',revisionSent:'0',status:'CONFIRMADO'},a),'CONFIRMADO');
  const {interactiveCard,handleTraceRoute}=await import('../cloudflare/teams-traceability.mjs');
  const worker=(await import('../cloudflare/worker.mjs')).default;
  const env={SUPABASE_URL:'https://database.test',SUPABASE_SECRET_KEY:'sb_secret_test',GRCON_TEAMS_CALLBACK_SECRET:'x'.repeat(48),GRCON_MICROSOFT_TENANT_ID:tenant,GRCON_TEAMS_TRACEABILITY_ENABLED:'true',POWER_AUTOMATE_EGRDT_WEBHOOK_URL:'https://qa.logic.azure.com/flow'};
  let flowCalls=0,flowPayload=null,flowFails=false,backendFails=false;
  global.fetch=async(url,options={})=>{
   url=String(url);
   if(url.includes('/auth/v1/user'))return Response.json({id:user,email:'qa@example.test'});
   if(url.includes('/grcon_memberships'))return Response.json([{role:'operator',active:true}]);
   if(url.includes('/rpc/grcon_teams_operation')){
    if(backendFails)return Response.json({message:'offline'},{status:503});
    const p=JSON.parse(options.body);
    try{return Response.json(await rpc(p.target_workspace,p.actor_id,p.operation,p.input));}catch(e){return Response.json({message:e.message,code:e.code},{status:400});}
   }
   if(url.startsWith('https://qa.logic.azure.com/')){flowCalls++;flowPayload=JSON.parse(options.body);return new Response('{}',{status:flowFails?500:202});}
   throw Error('Unexpected fetch '+url);
  };
  const outbound=attemptId=>new Request('https://grcon.test/api/egrdt-teams-notification',{method:'POST',headers:{authorization:'Bearer session','content-type':'application/json'},body:JSON.stringify({eventType:'EGRDT_READY_FOR_SIGEM',eventId:'egrdt-ready:client123',attemptId,source:{workspaceId:w,historyRecordId:hid,clientRecordId:'client123'},egrdt:{number,items:[{document:'FAKE-DOC',revision:'Z'}]},confirmation:{folderConfirmed:true},destination:{name:'Qualidade - Documentação'}})});
  const sendId=randomUUID();const sent=await worker.fetch(outbound(sendId),env);
  assert.equal(sent.status,200);assert.equal((await sent.json()).receiptOnly,true);
  assert.equal(flowPayload.egrdt.items[0].document,'DOC-001','canonical history defeats spoofed payload');
  assert.equal(flowPayload.message.adaptiveCard.actions[0].title,'✅ Postado');
  assert.equal(flowPayload.message.adaptiveCard.actions[1].type,'Action.ShowCard');
  assert.equal(JSON.stringify(flowPayload).includes(env.GRCON_TEAMS_CALLBACK_SECRET),false);
  await worker.fetch(outbound(sendId),env);assert.equal(flowCalls,1,'same request never reposts the card');
  flowFails=true;const failedId=randomUUID();assert.equal((await worker.fetch(outbound(failedId),env)).status,502);
  assert.equal((await rpc(w,user,'detail',{attemptId:failedId})).attempt.delivery_status,'failed');
  flowFails=false;backendFails=true;const before=flowCalls;assert.equal((await worker.fetch(outbound(randomUUID()),env)).status,503);assert.equal(flowCalls,before,'persistence failure never sends an untracked card');backendFails=false;
  const callback=(data,secret=env.GRCON_TEAMS_CALLBACK_SECRET)=>new Request('https://grcon.test/api/egrdt-teams/callback',{method:'POST',headers:{authorization:'Bearer '+secret},body:JSON.stringify(data)});
  const data={...confirm,attemptId:sendId,workspaceId:w,messageId:'sent-card',event:'confirm',type:'partial',selection:'0'};
  assert.equal((await handleTraceRoute(callback(data,'bad'),env)).status,401);
  assert.equal((await handleTraceRoute(callback({...data,responder:{...data.responder,tenantId:randomUUID()}}),env)).status,403);
  assert.equal((await handleTraceRoute(callback({...data,selection:'9'}),env)).status,400);
  const confirmed=await handleTraceRoute(callback(data),env);assert.equal(confirmed.status,200);const result=await confirmed.json();
  assert.equal(result.publishConfirmation,true);assert.equal(result.updatedCard.actions,undefined,'confirmed card removes interactive actions');
  assert.match(JSON.stringify(result.updatedCard),/DOC-001 · Rev. 0/,'updated card retains original document and revision');
  assert.match(JSON.stringify(result.updatedCard),/Construção/,'updated card retains issue purpose');
  assert.match(JSON.stringify(result.updatedCard),/DOC-002 · Rev. A/,'partial confirmation retains pending documents');
  assert.match(result.confirmationText,/João Silva/);
  const claim=await handleTraceRoute(callback({...data,event:'claim_notice'}),env);assert.equal((await claim.json()).publishConfirmation,true);
  const dupe=await handleTraceRoute(callback(data),env);assert.equal((await dupe.json()).publishConfirmation,false);
  const ack=await handleTraceRoute(callback({...data,event:'notice_sent',replyMessageId:'reply1'}),env);assert.equal(ack.status,200);
  assert.equal((await rpc(w,user,'detail',{attemptId:sendId})).attempt.notice_status,'sent');
  assert.equal((await handleTraceRoute(callback({...data,messageId:'other-card'}),env)).status,400);
  assert.throws(()=>interactiveCard({message:{adaptiveCard:{body:[{type:'TextBlock',text:'x'.repeat(30000)}]}}},a),/limite/);
  // Exact append-only legacy columns and Excel round-trip, including workers' options.
  global.location={href:'https://grcon.test/'};global.ExcelJS=require('../exceljs.min.js');global.GrconTeamsTraceCore=Core;
  const HistoryReport=require('../history_report.js'),Conference=require('../posting_conference_core.js');
  global.GrconPostingConference=Conference;const ConferenceReport=require('../posting_conference_report.js');
  global.fetch=async()=>new Response(null,{status:404});
  const rec={id:'client123',clientRecordId:'client123',cloudId:hid,workspaceId:w,egrdtNumber:number,generatedAt:'2026-10-09T12:00:00Z',files,documentCount:2};
  const workbook=new global.ExcelJS.Workbook();await workbook.xlsx.load(await HistoryReport.buildWorkbook([rec],{teamsAttempts:[a]}));
  const historyRows=HistoryReport.egrdtRows([rec],{teamsAttempts:[a]});assert.equal(historyRows[0]['Enviado ao Teams?'],'Sim');
  assert.ok(Object.keys(historyRows[0]).includes('DATA DA GERAÇÃO / POSTAGEM'));assert.ok(Object.keys(historyRows[0]).includes('PROPÓSITO(S) DA GRDT'));
  const historyDocs=HistoryReport.documentRows([rec],{teamsAttempts:[a]});assert.equal(historyDocs[0]['STATUS SIGEM'],'Em análise');assert.equal(historyDocs[1]['Documento declarado como postado?'],'Não');
  const rows=Conference.reconcile([rec],[],{}, {now:'2026-10-09T15:00:00Z'}).rows;
  const pending=new global.ExcelJS.Workbook();await pending.xlsx.load(await ConferenceReport.buildWorkbook(rows,{pending:true,teamsAttempts:[a],workspaceId:w,groups:Conference.aggregateByGrdt(rows)}));
  assert.deepEqual(pending.worksheets.map(s=>s.name),['Detalhamento']);
  assert.equal(pending.getWorksheet('Detalhamento').getCell('E10').value,'Data eGRDT');
  assert.equal(pending.getWorksheet('Detalhamento').getCell('S10').value,'Enviado ao Teams?');
  assert.equal(pending.getWorksheet('Detalhamento').getCell('S11').value,'Sim');
  const consult=require('../requests_report.js'),book=new global.ExcelJS.Workbook(),sheet=book.addWorksheet('Consulta');
  consult.writeConsultationSheet(sheet,[{document:'DOC-001',...Core.columns(a,files[0])}],{columns:[{key:'document',header:'Documento'}],teamsHeaders:Core.headers});
  assert.ok([...sheet.getColumn(2).values].includes('Sim'));
  const large=Array.from({length:30000},(_,i)=>({...a,id:String(i),history_id:'h'+i,client_record_id:'c'+i}));
  const started=performance.now(),largeIndex=Core.index(large);for(let i=0;i<30000;i++)assert.equal(Core.attemptsFor({workspaceId:w,id:'h'+i},largeIndex).length,1);
  assert.ok(performance.now()-started<4000,'batch index handles 30k records without per-line network calls');
  console.log('Teams traceability: database, Worker, identity, partial/total, duplicate, expiry, reports and 30k index PASS');
 }finally{global.fetch=originalFetch;await db.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
