'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { PGlite } = require('@electric-sql/pglite');
const root = path.resolve(__dirname,'..');
const owner='00000000-0000-4000-8000-000000000010', admin='00000000-0000-4000-8000-000000000011', viewer='00000000-0000-4000-8000-000000000012';
const workspace='00000000-0000-4000-8000-000000000001';
(async()=>{
 const db=new PGlite();
 try {
  await db.exec(`create schema private; create schema auth; create role anon; create role authenticated;
   grant usage on schema private,public,auth to authenticated;
   create function auth.uid() returns uuid language sql as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
   create table public.grcon_workspaces(id uuid primary key default gen_random_uuid(),name text,created_by uuid,created_at timestamptz default now());
   create table public.grcon_memberships(workspace_id uuid,user_id uuid,role text,active boolean default true,invited_by uuid,joined_at timestamptz default now(),primary key(workspace_id,user_id));
   alter table public.grcon_memberships enable row level security;
   grant select,insert,update,delete on public.grcon_memberships to authenticated;
   create function private.grcon_is_member(w uuid) returns boolean language sql security definer set search_path=public as $$ select auth.uid() is not null and exists(select 1 from grcon_memberships where workspace_id=w and user_id=auth.uid() and active) $$;
   create function private.grcon_has_role(w uuid,roles text[]) returns boolean language sql security definer set search_path=public as $$ select auth.uid() is not null and exists(select 1 from grcon_memberships where workspace_id=w and user_id=auth.uid() and active and role=any(roles)) $$;
   create policy members_select on public.grcon_memberships for select to authenticated using(private.grcon_is_member(workspace_id));
   create table public.grcon_history(id uuid primary key default gen_random_uuid(),workspace_id uuid,generated_at timestamptz,deleted_at timestamptz);
   create table public.grcon_audit_events(workspace_id uuid,actor_id uuid,action text,entity_type text,entity_id text,metadata jsonb,created_at timestamptz default now());
   insert into public.grcon_workspaces(id,name) values('${workspace}','GRCON');
   insert into public.grcon_memberships(workspace_id,user_id,role) values('${workspace}','${owner}','owner'),('${workspace}','${admin}','admin'),('${workspace}','${viewer}','viewer');`);
  for(const file of ['20260929223549_shared_sigem_query.sql','20261006183921_multi_contract_foundation.sql','20261006184001_sigem_status_monitoring_schema.sql','20261006184118_sigem_status_monitoring_engine.sql','20261006184204_sigem_status_monitoring_api.sql','20261006184250_email_template_versioning_schema.sql','20261006184304_email_template_versioning_read_api.sql','20261006184322_email_template_versioning_write_api.sql',fs.readdirSync(path.join(root,'supabase/migrations')).find(f=>f.endsWith('_grcon_integrated_contract_monitoring_hardening.sql'))]) await db.exec(fs.readFileSync(path.join(root,'supabase/migrations',file),'utf8'));
  const as=async(id,role='authenticated')=>db.exec(`reset role; set request.jwt.claim.sub='${id}'; set role ${role};`);
  await as(owner);
  const contexts=(await db.query('select * from public.grcon_contract_context()')).rows;
  assert.equal(contexts.length,5); assert.equal(contexts[0].code,'UHDT-D');
  const other=contexts.find(c=>c.code==='UGH').workspace_id;
  const migrated=(await db.query('select count(*)::integer n from public.grcon_memberships where workspace_id=$1 and contract_id is not null',[workspace])).rows[0].n;assert.equal(migrated,3);
  assert.equal((await db.query('select count(*)::integer n from public.grcon_contracts')).rows[0].n,5,'owner RLS executes correctly');
  const rpc=(name,args)=>db.query('select * from public.'+name+'('+args.map((_,i)=>'$'+(i+1)).join(',')+')',args);
  await rpc('grcon_monitored_document_save',[workspace,{documentCode:'DOC-001',priority:'alta',note:'QA'}]);
  const row=(code,status,revision='0')=>({document:code,status,revision,title:'Teste',discipline:'Elétrica'});
  async function publish(rows, expected=null, target=workspace) {
    const begun=await rpc('grcon_sigem_query_begin',[target,'QA.xlsx',rows.length,{checksum:'test'},expected]);
    const id=begun.rows[0].grcon_sigem_query_begin;
    await rpc('grcon_sigem_query_chunk',[target,id,1,rows]);
    await rpc('grcon_sigem_query_publish',[target,id]);return id;
  }
  const first=await publish([row('DOC-001','Em análise'),row('DOC-002','Emitido'),row('DOC-003','Aprovado')]);
  const second=await publish([row('DOC-001','Emitido'),row('DOC-002','Em workflow'),row('DOC-003','Aprovado')],first);
  let comparisons=(await rpc('grcon_sigem_comparison_history',[workspace])).rows;
  assert.equal(comparisons[0].counts.leftAnalysis,1);assert.equal(comparisons[0].counts.enteredAnalysis,1);assert.equal(comparisons[0].counts.changes,2);
  let notices=(await rpc('grcon_notifications_list',[workspace,false,100])).rows;
  assert.equal(notices.length,1);assert.equal(notices[0].kind,'MONITORED_LEFT_ANALYSIS');assert.equal(notices[0].severity,'high');assert.equal(notices[0].is_read,false);
  assert.equal((await rpc('grcon_notifications_unread_count',[workspace])).rows[0].grcon_notifications_unread_count,1);
  await rpc('grcon_notifications_mark_read',[workspace,[notices[0].id]]);
  assert.equal((await rpc('grcon_notifications_unread_count',[workspace])).rows[0].grcon_notifications_unread_count,0);
  const identical=await publish([row('DOC-001','Emitido'),row('DOC-002','Em análise'),row('DOC-003',' Aprovado ')],second);
  comparisons=(await rpc('grcon_sigem_comparison_history',[workspace])).rows;
  assert.equal(comparisons[0].counts.changes,0,'workflow/analysis and spaces are operationally equivalent');
  assert.equal((await rpc('grcon_notifications_list',[workspace,false,100])).rows.length,1,'reimport creates no duplicate alert');
  await rpc('grcon_sigem_compare_versions',[workspace,first,second]);
  assert.equal((await rpc('grcon_notifications_list',[workspace,false,100])).rows.length,1,'manual comparison is read-only for alerts');
  await assert.rejects(publish([row('DOC-001','Emitido'),row('DOC-001','Em análise')],identical),/conflitantes/);
  assert.equal((await rpc('grcon_sigem_query_current',[workspace])).rows[0].snapshot_id,identical,'conflicting load keeps previous snapshot active');
  const otherFirst=await publish([row('DOC-001','Emitido')],null,other);
  await assert.rejects(rpc('grcon_sigem_compare_versions',[workspace,first,otherFirst]),/Versões indisponíveis/);
  await as(viewer);
  assert.equal((await rpc('grcon_notifications_unread_count',[workspace])).rows[0].grcon_notifications_unread_count,1,'publisher reading does not read the viewer alert');
  const viewerNotices=(await rpc('grcon_notifications_list',[workspace,true,100])).rows;
  assert.equal(viewerNotices[0].id,notices[0].id,'all contract members receive the same monitored transition');
  await rpc('grcon_notifications_mark_read',[workspace,[notices[0].id]]);
  assert.equal((await rpc('grcon_notifications_unread_count',[workspace])).rows[0].grcon_notifications_unread_count,0);
  assert.equal((await rpc('grcon_contract_context',[])).rows.length,1);
  await assert.rejects(rpc('grcon_sigem_versions',[other]),/Sem acesso/);
  await assert.rejects(rpc('grcon_monitored_document_save',[workspace,{documentCode:'DENIED'}]),/permissão|administrador|proprietário/i);
  await assert.rejects(rpc('grcon_email_template_save',[workspace,'contract',{columns:['DOCUMENTO']}]),/administrador/);
  await as(admin);
  await assert.rejects(db.query("update public.grcon_memberships set role='owner' where workspace_id=$1 and user_id=$2",[workspace,admin]),/row-level security/);
  const model=await rpc('grcon_email_template_save',[workspace,'contract',{columns:['DOCUMENTO'],styles:{fontFamily:'Arial'}}]);
  const saved=model.rows[0].grcon_email_template_save;
  await rpc('grcon_email_template_save',[workspace,'contract',{columns:['REVISÃO']}]);
  await rpc('grcon_email_template_restore',[workspace,saved]);
  const activeModel=(await rpc('grcon_email_template_get',[workspace])).rows[0]; assert.equal(activeModel.version,3); assert.deepEqual(activeModel.configuration.columns,['DOCUMENTO']);
  assert.equal((await rpc('grcon_email_template_versions',[workspace])).rows.length,3);
  await assert.rejects(rpc('grcon_email_template_save',[workspace,'global',{}]),/proprietário/);
  await as(owner);await rpc('grcon_email_template_save',[workspace,'global',{columns:['TÍTULO']}]);
  assert.deepEqual((await rpc('grcon_email_template_get',[other])).rows[0].configuration.columns,['TÍTULO'],'global fallback');
  await as('', 'anon');await assert.rejects(rpc('grcon_sigem_versions',[workspace]),/permission denied/);
  await as(viewer);await assert.rejects(db.query('select private.grcon_run_sigem_comparison($1,$2,$3,true)',[workspace,first,second]),/permission denied/);
  console.log('Integrated contracts/monitoring: migration, RLS, status transitions, duplicate/conflict atomicity, manual comparisons, alerts/read state and email versions passed.');
 } finally {await db.close();}
})().catch(error=>{console.error(error);process.exitCode=1;});
