const assert = require('node:assert/strict');
const N = require('../n381_concordance.js');
const V = require('../normative_version_registry.js');
const expected = { documentNumber: 'ET-5290.00-22313-91B-C1O-002', revision: 'B', title: 'ESPECIFICACAO TECNICA', category: 'ET' };
const page = (revision = 'B', number = 1, code = expected.documentNumber) => N.extractPage([`DOCUMENTO: ${code}`, `REVISAO: ${revision}`, 'TITULO: ESPECIFICACAO TECNICA', 'CATEGORIA: ET', 'FOLHA: 1 DE 2'], number, { widthMm: 210, heightMm: 297 });
const inspection = pages => ({ status: 'complete', totalPages: 2, pages });
const audit = extra => N.audit({ expected, inspection: inspection([page('B', 1), page('B', 2)]), ...extra });
assert.equal(audit().blocks.length, 0);
assert.equal(audit().warnings[0].ruleId, 'n381.scope');
assert.equal(audit({ inspection: inspection([page('A', 2)]) }).blocks[0].ruleId, 'n381.page.2.revision');
assert.equal(audit({ inspection: inspection([page('A', 2)]), revisionBySheet: true }).blocks.length, 0);
assert.equal(audit({ inspection: inspection([page('A', 1)]), replaceFirstPage: true }).blocks.length, 0);
assert.equal(audit({ inspection: inspection([page('A', 1)]), replaceFirstPage: false }).blocks.length, 1);
assert.equal(audit({ inspection: inspection([page('B', 2, 'ET-OUTRO')]), revisionBySheet: true }).blocks.length, 1);
assert.equal(audit({ inspection: inspection([page('B', 2, 'ET-OUTRO')]), applicability: 'not-applicable' }).blocks.length, 1);
const ambiguous = N.extractPage(['REVISAO: A', 'REVISAO: B'], 1);
assert.deepEqual(ambiguous.ambiguous, ['revision']);
assert.equal(ambiguous.values.revision, undefined);
assert.equal(audit({ inspection: inspection([ambiguous]) }).blocks.length, 0);
assert.equal(N.extractPage(['REVISAO A B C', 'Rev. anterior A; revisão nova B', 'ARQUIVO.pdf'], 1).values.revision, undefined);
assert.equal(N.extractPage([`DOCUMENTO: ${expected.documentNumber} REVISAO: B FOLHA: 1 DE 2`]).values.revision, 'B');
assert.equal(N.extractPage([`DOCUMENTO: ${expected.documentNumber} REV. A OUTROS CAMPOS`]).values.documentNumber, undefined, 'Texto de campos vizinhos não pode virar número divergente.');
assert.equal(audit({ inspection: inspection([N.extractPage([])]) }).blocks.length, 0);
assert.ok(audit({ inspection: inspection([N.extractPage([])]) }).warnings.some(r => r.ruleId.endsWith('inconclusive')));
assert.ok(audit({ inspection: { status: 'partial', totalPages: 300, pages: [page()] } }).warnings.some(r => r.ruleId === 'n381.pdf.partial'));
const cover = { executor: 'ANA', checker: 'ANA', approver: 'CARLOS', revisionDate: '02/10/2026' };
assert.equal(audit({ cover }).blocks.length, 0);
assert.equal(audit({ cover, applicability: 'confirmed' }).blocks.length, 0, 'Escopo confirmado não promove texto com emendas não auditadas.');
const completeVersions = V.createVersionRegistry(V.SEED);
completeVersions.register({ norm: 'N-0381', part: 'amendments', revision: 'M', status: 'active', sourceAvailable: true, verificationSource: 'Fonte completa confirmada no cenário unitário' });
assert.equal(audit({ cover, applicability: 'confirmed', versions: completeVersions }).blocks[0].ruleId, 'n381.cover.distinct-responsibles');
completeVersions.register({ ...completeVersions.get('N-0381', 'amendments'), revision: 'N' }, { replace: true });
assert.equal(audit({ cover, applicability: 'confirmed', versions: completeVersions }).blocks.length, 0, 'Emendas de outra revisão não promovem uma regra M.');
completeVersions.register({ ...completeVersions.get('N-0381', 'amendments'), revision: 'M' }, { replace: true });
assert.equal(audit({ cover, applicability: 'not-applicable' }).blocks.length, 0);
assert.ok(audit({ cover: { ...cover, executor: '' }, applicability: 'confirmed', versions: completeVersions }).blocks.some(r => r.ruleId === 'n381.cover.executor'));
assert.equal(audit({ cover: { ...cover, checker: 'BRUNO' }, applicability: 'confirmed' }).blocks.length, 0);
const references = [{ source: 'LD', document: expected.documentNumber, revision: 'A', title: expected.title }, { source: 'Histórico / GRDT antiga', document: expected.documentNumber, revision: '0' }];
assert.equal(audit({ references }).blocks.length, 0, 'Revisões históricas nunca substituem a revisão manual de destino.');
assert.equal(audit({ references }).references[1].revision, '0');
assert.ok(audit({ references: [{ ...references[0], title: 'OUTRO TITULO' }] }).warnings.some(r => r.ruleId.includes('reference')));
const stale = V.createVersionRegistry(V.SEED);
stale.register({ ...stale.get('N-0381'), revision: 'N', catalogRevision: 'N' }, { replace: true });
assert.equal(audit({ inspection: inspection([page('A', 2)]), versions: stale }).blocks.length, 0);
assert.ok(audit({ inspection: inspection([page('A', 2)]), versions: stale }).warnings.some(r => r.code === 'rule_revision_mismatch'));
const historical = JSON.stringify(audit());
N.versions.register({ ...N.versions.get('N-0381'), status: 'unconfirmed' }, { replace: true });
assert.equal(audit({ inspection: inspection([page('A', 2)]) }).blocks.length, 0);
assert.equal(JSON.parse(historical).concordanceVersion, N.VERSION);
console.log('n381_concordance: ok — divergências, escopo, revisão por folha, extração ambígua, fonte e snapshots');
