"use strict";
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const root = path.resolve(__dirname, "..");
const read = name => fs.readFileSync(path.join(root, name), "utf8");
const html = read("index.html");
const avatar = read("grcon-profile-avatar.js");
const css = read("grcon-profile-avatar.css");
const vc = read("grcon-version-c.css");
const migration = read("supabase/migrations/20261009212000_grcon_profile_photos.sql");

assert.match(html, /grcon-version-c\.css/);
assert.match(html, /grcon-profile-avatar\.css/);
assert.match(html, /grcon-profile-avatar\.js/);
assert.ok(html.indexOf('src="grcon_cloud_app.js"') < html.indexOf('src="grcon-profile-avatar.js"'));
assert.match(html, /img-src[^;]+https:\/\/kvyrttccwzdhasplfxnr\.supabase\.co/);
assert.match(avatar, /grcon:cloud-ready/);
assert.match(avatar, /grcon:cloud-signed-out/);
assert.match(avatar, /createSignedUrl\(keyFor\(id\), SIGNED_URL_TTL\)/);
assert.match(avatar, /\.upload\(keyFor\(id\), photo/);
assert.match(avatar, /\.remove\(\[keyFor\(id\)\]\)/);
assert.match(avatar, /new Set\(\["image\/jpeg", "image\/png", "image\/webp"\]\)/);
assert.match(avatar, /canvas\.toBlob\(resolve, "image\/webp", 0\.82\)/);
assert.match(avatar, /session\(\)\?\.user\?\.id !== id/);
assert.match(avatar, /MAX_SOURCE_BYTES = 6 \* 1024 \* 1024/);
assert.match(avatar, /MAX_STORED_BYTES = 1024 \* 1024/);
assert.match(migration, /false,1048576,array\['image\/webp'\]/);
assert.equal((migration.match(/name = auth\.uid\(\)::text \|\| '\/avatar\.webp'/g) || []).length, 5);
assert.match(migration, /for select to authenticated/);
assert.match(migration, /for insert to authenticated/);
assert.match(migration, /for update to authenticated/);
assert.match(migration, /for delete to authenticated/);
assert.match(migration, /m\.user_id=auth\.uid\(\) and m\.active/);
assert.match(css, /grcon-cloud-account-avatar/);
assert.match(vc, /grid-template-columns: minmax\(206px, 218px\)/);
assert.doesNotMatch(vc, /display:\s*none\s*!important\s*;.*\.ops-sidebar/);
console.log("OK — avatar privado e lapidação visual versão C: integrações e RLS verificadas.");
