import { useEffect, useRef } from "react";
import type { SigemPwState } from "../types/domain";
function fmt(value:number):string{return Number(value||0).toLocaleString("pt-BR");}
function fmtDate(value:unknown):string{const source=value==null?"":String(value);const date=new Date(source);return source&&!Number.isNaN(date.getTime())?new Intl.DateTimeFormat("pt-BR",{dateStyle:"short",timeStyle:"short"}).format(date):"—";}
export function SigemPwBaseHistoryDialog({state,onClose,onEdit,onDelete,onSelectShared,onDeleteShared}:{state:SigemPwState;onClose():void;onEdit(kind:"sigem"|"pw",snapshotId:string):void;onDelete(snapshotId:string):void;onSelectShared(snapshotId:string):void;onDeleteShared(snapshotId:string):void;}) {
 const ref=useRef<HTMLDialogElement>(null);
 useEffect(()=>{const dialog=ref.current;if(!dialog)return;if(state.historyDialogOpen&&!dialog.open)dialog.showModal?.();if(!state.historyDialogOpen&&dialog.open)dialog.close();},[state.historyDialogOpen]);
 const snapshots=[...(state.history.snapshots||[])].sort((a,b)=>(window.GrconSigemPwDashboard?.parseDateMs(b.meta.importedAt)||0)-(window.GrconSigemPwDashboard?.parseDateMs(a.meta.importedAt)||0));
 const labels:Record<string,string>={sigem:"SIGEM",pw:"PW",ld:"LD"};
 const canManage=Boolean(window.GrconSharedSigemQuery?.canPublish?.());
 return <dialog ref={ref} className="spw-history" id="spw-base-history" onClose={onClose}><header className="spw-history-head"><div><span className="spw-kicker">BASES IMPORTADAS</span><h3>Gerenciar histórico</h3></div><button className="secondary-button" id="spw-base-history-close" type="button" onClick={onClose}>Fechar</button></header><div className="spw-history-body" id="spw-base-history-body">
 <section className="spw-shared-history"><div className="spw-history-section-title"><strong>Consulta Geral compartilhada</strong><small>A base marcada como ATUAL alimenta o SIGEM × PW para todos os usuários.</small></div>
 {state.sharedSigemHistory.length?state.sharedSigemHistory.map((item)=><div className="spw-history-row" key={item.snapshotId}><div className="spw-history-kind">SIGEM</div><div><strong>{item.fileName||"Base sem nome"}{item.isActive&&<span className="spw-current">ATUAL</span>}</strong><small>{fmtDate(item.publishedAt||item.createdAt)} · {fmt(item.recordCount)} registros</small></div><div className="spw-history-actions">{!item.isActive&&<button className="secondary-button" type="button" disabled={!canManage} onClick={()=>onSelectShared(item.snapshotId)}>Selecionar como atual</button>}<button className="secondary-button danger-button" type="button" disabled={!canManage} onClick={()=>onDeleteShared(item.snapshotId)}>Excluir</button></div></div>):<div className="spw-empty compact"><div><strong>Nenhuma Consulta Geral ativa</strong><span>Carregue e publique uma nova base para reativar o SIGEM.</span></div></div>}
 </section>
 <section><div className="spw-history-section-title"><strong>Histórico local do comparativo</strong><small>Snapshots usados pela rastreabilidade e evolução deste navegador.</small></div>
 {snapshots.length?snapshots.map((item)=>{const kind=String(item.meta.kind||"");const currentId=kind==="sigem"||kind==="pw"||kind==="ld"?state[kind].meta?.snapshotId:"";const current=currentId===item.meta.snapshotId;const editable=kind==="sigem"||kind==="pw";const original=item.meta.sourceImportedAt&&item.meta.sourceImportedAt!==item.meta.importedAt?` · original ${fmtDate(item.meta.sourceImportedAt)}`:"";return <div className="spw-history-row" key={String(item.meta.snapshotId)}><div className="spw-history-kind">{labels[kind]||"BASE"}</div><div><strong>{String(item.meta.fileName||"Base sem nome")}{current&&<span className="spw-current">ATUAL</span>}</strong><small>Data da base {fmtDate(item.meta.importedAt)}{original} · {fmt(item.records.length)} registros armazenados</small></div><div className="spw-history-actions">{editable&&<button className="secondary-button" type="button" onClick={()=>onEdit(kind as "sigem"|"pw",String(item.meta.snapshotId))}>Editar data</button>}<button className="secondary-button" type="button" onClick={()=>onDelete(String(item.meta.snapshotId))}>Excluir snapshot local</button></div></div>;})
 :<div className="spw-empty compact"><div><strong>Histórico local vazio</strong><span>As próximas importações aparecerão aqui.</span></div></div>}
 </section></div></dialog>;
}
