import type { SigemPwState } from "../types/domain";
function fmt(value:number):string{return Number(value||0).toLocaleString("pt-BR");}
function Card({label,value,css,note,available}:{label:string;value:number;css:string;note:string;available:boolean}){return <article className={`spw-kpi ${css}`}><span>{label}</span><strong>{available?fmt(value):"—"}</strong><small>{note}</small></article>;}
export function SigemPwSituationCards({state}:{state:SigemPwState}){const s=state.result?.summary;const both=Boolean(state.sigem.meta&&state.pw.meta);return <><section className="spw-actions-grid" id="spw-actions-grid" aria-label="Situações exclusivas entre as bases">
<Card label="SIGEM: falta cadastrar no PW" value={s?.sigemOnly||0} css="" note="Postado no SIGEM; código + revisão ainda não cadastrados no PW." available={both}/>
<Card label="SIGEM + PW: ainda não emitido" value={s?.bothNotEmitted||0} css="warn" note="Postado no SIGEM e cadastrado no PW; se o PW não informar a revisão, a presença é confirmada pelo código. Falta evidência de emissão no PW." available={both}/>
<Card label="SIGEM + PW: emitido" value={s?.bothEmitted||0} css="ok" note="Postado no SIGEM e emitido no PW; a revisão é usada quando informada." available={both}/>
<Card label="Só PW: ainda não emitido" value={s?.pwOnlyNotEmitted||0} css="pw warn" note="Cadastrado no PW, sem emissão e não localizado no SIGEM." available={both}/>
<Card label="Só PW: emitido" value={s?.pwOnlyEmitted||0} css="pw" note="Emitido no PW, mas o código + revisão não foi localizado no SIGEM." available={both}/>
</section><p className="spw-classification-note" id="spw-classification-note">{both?<><strong>Contagem conciliada:</strong> {fmt(s?.classifiedTotal||0)} registro(s) distribuídos uma única vez entre as cinco situações. Revisão ausente no PW é conciliada pelo código do documento.</>:"Carregue as bases SIGEM e PW para obter a classificação completa."}</p></>;}